### ISSUE TITLE
Entity Component System

### ISSUE THREAD

**Issue by LithiumToast** [craftworkgames/MonoGame.Extended#100]
What do you guys think of adding an [Entity Component System](https://en.wikipedia.org/wiki/Entity_component_system)?

**Comment by craftworkgames** [comment]
I wrote an [entity component system](https://github.com/craftworkgames/Astrid.Framework/tree/master/Astrid.Framework/Components) once and part of an old (failed) game framework. It was really fun to write and works pretty well.

Is it a good fit for MonoGame.Extended?  Probably, but we'd have to think carefully about how it fits in with the rest of the framework. I wouldn't want to force it upon people that they have to use an ECS.

For example, in an ECS you usually have some sort of transform component (position, rotation, scale) and a separate sprite component (textureRegion, color, origin, visibility).

The way we have it now; those 2 concepts are combined in the `Sprite` class. I suppose what we could do is keep the ECS code in a separate namespace and make sure all the component classes are named appropriately. Like, `SpriteComponent` for example. 

This kind of thing has crossed my mind a couple of times. An ECS is certainly a nice way to avoid the deep and wide inheritance hierarchies.

**Comment by cupstudio** [comment]
Component is a great pattern, and I've tackled it myself once as an exercise.  The trickiest part for me was communication among the components themselves.  Use a global message queue?  Dependent components get copies of each other?  The entity itself sends and receives messages among its components?  Have all attributes live inside the Entity to be manipulated directly?  There are a lot of options out there with + and - to each, so I'd love to see how someone more experienced handles it.

I think a very light component system with Interfaces and / or base abstract classes could be doable, just make it really easy to extend.

**Comment by craftworkgames** [comment]
> The trickiest part for me was communication among the components themselves.

Yeah, this is always the challenge. I remember trying lots of different designs in my system. From my vague recollection I recall doing something like this that kinda worked pretty well.

   var transform = entity.AddComponent(new TranformComponent());
   var physics = entity.AddComponent(new PhysicsComponent(transform, shape, mass));
   var sprite = entity.AddComponent(new SpriteComponent(transform, textureRegion));

The idea was to essentially *glue* components together with a 3rd component. In this example, the physics component moves the sprite component around using a transform component. The cool thing about this was that you could attach a physics component to anything that could be transformed (e.g. sprites, camera, particle emitters, etc).

Btw.. I'm not advocating this as the way we need to do it in MonoGame.Extended. I just want to start a discussion about the pros and cons of different approaches.

**Comment by cupstudio** [comment]
If I'm reading that correctly, each component has a copy of any required components needed.  

Also, I like the idea of keeping any number of `IEntityComponent`s in a list or similar in the entity (or the entities `ComponentManager` if its complicated enough to warrant such), so you can add multiples of the same base (i.e. multiple AI components or multiple physics / collisions etc).   This gives great flexibility and also how I did mine.

**Comment by LithiumToast** [comment]
Something like this? You would call `entityInstance.Components.Get<MyComponent>();` to query if the entity has a component of the specific type.

```    
    public sealed class Entity
    {
        ...
        public EntityComponentCollection Components { get; }

        internal Entity()
        {
            Components = new EntityComponentCollection(this);
        }
    }

    public sealed class EntityComponentCollection : ...
    {
        private readonly List<EntityComponent> _components = new List<EntityComponent>();
        private readonly Dictionary<Type, EntityComponent> _componentsByType = new Dictionary<Type, EntityComponent>();
        ....

        public T Add<T>() where T : EntityComponent, new()
        {
            ...
        }

        public bool Remove<T>() where T : EntityComponent, new()
        {
            ...
        }

        public T Get<T>() where T : EntityComponent
        {
            var type = typeof (T);
            EntityComponent component;
            if (!_componentsByType.TryGetValue(type, out component))
            {
                return null;
            }
            return (T)component;
        }
    }

    public abstract class EntityComponent
    {
...
    }
```







I also implemented my own version of ECS. The way I did it was to have a Dictionary<Type, >

**Comment by craftworkgames** [comment]
> Components = new EntityComponentCollection(this);

I really like the way you created an entity component collection class and pass in a reference to the entity. Why didn't I think of that :smiley:

**Comment by LithiumToast** [comment]
> pass in a reference to the entity

In my implementation this is so in the `Add` method of `EntityComponentCollection` can create an `EntityComponent` using object pooling and pass the `Entity` instance to the `EntityComponent`. This allows for an `EntitySystem`, when it does something with an `EntityComponent`, to have a reference to the `Entity` instance and query for other `EntityComponent`s.

Here's my `SpriteRenderSystem` which processes a `SpriteComponent` and queries for a `TransformComponent` using this technqiue.

```
    public sealed class SpriteRenderSystem : EntitySystem<SpriteComponent>
    {
...
        public SpriteRenderSystem()
            : base(EntitySystemProcessingType.Draw)
        {
...
        }

        protected internal override void Process(GameTime gameTime)
        {
            _spriteBatch.Begin(...);

            base.Process(gameTime);

            _spriteBatch.End(...);
        }

        protected override void ProcessComponent(GameTime gameTime, SpriteComponent component)
        {
            var entity = component.Entity;
            var transform = entity.Components.Get<TransformComponent>;
            var position = transform?.Position.ToVector2() ?? Vector2.Zero;
            var rotation = transform?.Rotation.Roll ?? 0; // z-rotation
            var scale = transform?.Scale.ToVector2() ?? Vector2.One;

            _spriteBatch.Draw(...);
        }
    }
```

**Comment by craftworkgames** [comment]
@LithiumToast I figured it was something like that. Thanks for sharing the details :smile:

**Comment by craftworkgames** [comment]
One thing I really miss from previous game engines I've worked on is an Entity Component System. So I'm thinking about resurrecting this issue.

**Comment by bsimser** [comment]
Just an update, I've been doing a lot of reading on ECSes built in the world and find it almost a better way to build games. A lot of information out there that is nice on how they're designed and built up, some things that could be applied here. 

One thing I noticed from a Unity based one I found [Entitas](https://github.com/sschmid/Entitas-CSharp) was a fluent interface for building up your entities. Rather than just having a bunch of calls to add components or services, you just build the entity up initially with the fluent interface to add whatever behaviors you want.

This seems like a nicer approach and dictates better intent on what you're trying to do. For example in the EntityComponentSystem demo instead of this:

```
var animatedEntity = _entityComponentSystem.CreateEntity("animated", new Vector2(50, 50));
animatedEntity.AttachComponent(new AnimatedSprite(motwAnimationFactory, "walkSouth"));
```

I would see you doing something like this:

```
var animatedEntity = _entityComponentSystem.GetPool().CreateEntity()
.WithName("animated")
.AtPosition(new Vector2(50, 50)
.IsAnimated()
.AddComponent(new AnimatedSprite(motwAnimationFactory).WithName("walkSouth"));
```

Or something like that. The intent is more descriptive. In the first example what is the Vector2? The size? The position? Also you don't have to go hunting for where the entities get created, there's only place and that's all you need to set it up.

Maybe give a look at the Unity library I linked to. I think it has some interesting ideas to solving some of these parts of an ECS.

**Comment by craftworkgames** [comment]
I've seen fluent interfaces before, they are very cool. Although, they do tend to be more work to actually write.

Entitas looks very cool. I wonder what it would take to get it working with MonoGame. Maybe that'd be a better option.

**Comment by bsimser** [comment]
Fluent interfaces are cheap and easy to write (in a nutshell you just set internal properties or fields and return "this"). Entitas does look cool but how would it fit into MGE? Looking at the [overview wiki page](https://github.com/sschmid/Entitas-CSharp/wiki/Overview) it's a handful of classes and 4 core objects:

- Entity
- Pool
- Group
- Component

MGE doesn't currently pull in or depend on anything external (like a Tiled library) so not sure how something like this would fit in and I don't think you want MGE to be dependent on it. People can feel free to choose to use it, but you can't bake it in and write a small wrapper around it or helper classes so not sure how you would fold it in. Another library I saw was [Nez](https://github.com/prime31/Nez) but it seems like a competitor to MGE and contains it's own RYO ECS (again, just a few classes).

I really like the idea of an ECS for MGE, but not sure how it would work as you don't want to reinvent the wheel but then you also don't want people to need to install 10 different libraries to get a full meal deal. Otherwise borrowing concepts from some of these other libraries and enhancing the ECS that's in the library now, but then you're just re-implementing something someone else did and that's no fun.

**Comment by craftworkgames** [comment]
Yeah, I dunno exactly how it would all fit together. I was more thinking that we could probably learn something from Entitas and maybe borrow some of the concepts.

I think the first step would be to simply see how difficult it is to get Entitas working with MonoGame regardless of MonoGame.Extended. That alone could be worthy of a github repo in itself. Then maybe at that point it makes sense to combine them in some way. Not sure.

> Another library I saw was Nez but it seems like a competitor to MGE and contains it's own RYO ECS (again, just a few classes).

One of the interesting things about Nez is that it started it's life by borrowing quite a bit of code from MonoGame.Extended. I don't see any reason why we can't also borrow concepts from Nez.

> MGE doesn't currently pull in or depend on anything external (like a Tiled library) so not sure how something like this would fit in and I don't think you want MGE to be dependent on it.

Yep I totally, agree. I don't want the core library to depend on Entitas. However, there may be other options. Perhaps we can have a fork of Entitas that works with extended or something.

> I really like the idea of an ECS for MGE, but not sure how it would work as you don't want to reinvent the wheel but then you also don't want people to need to install 10 different libraries to get a full meal deal. 

At the end of the day the goal to create games. I think an ECS is a really nice way to do that. The question is about how an ECS fits into MonoGame.Extended? Maybe it's part of the core library, maybe it's not. Maybe we fork an existing library, or perhaps we roll our own. 

Obviously, I've made a start on integrating some ECS concepts into the library, but it's by no means complete. I'm certainly open to other ideas and I'd be willing to scrap it in favor of something better if it makes sense to do so.

**Comment by craftworkgames** [comment]
I think the next batch of work on this is #305
