### ISSUE TITLE
[Documentation] Let's Improve the github Wiki

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#104]
When I first started MonoGame.Extended I didn't take much notice of the [awesome wiki](https://github.com/craftworkgames/MonoGame.Extended/wiki) functionality that github provides. Instead I posted things like ["How to install MonoGame.Extended"](http://www.dylanwilson.net/how-to-install-monogame-extended) on my blog.

I believe that was a mistake. MonoGame.Extended is open source and the documentation belongs in a wiki so everyone can contribute and edit it. I'm going to start moving over the relevant blog posts shortly.

What we want to end up with is some awesome documentation. Something the [LibGDX wiki](https://github.com/libgdx/libgdx/wiki).

If anyone has something to contribute. Please, start making pages.

**Comment by craftworkgames** [comment]
I started moving some of my tutorials over from my blog to the github wiki. I think this is a better place for them so that everyone has the ability to edit and improve them.

Anyone want to do some proof reading? :+1:

**Comment by LithiumToast** [comment]
@craftworkgames For the roadmap I see Mac OS is not a supported platform? I use a Mac as my development machine and virtualize Windows just to get Visual Studio + ReSharper :smile:. Xamarin Studio + MonoGame 3.4 + MonoMac seem to work fine for MG.Ex with the Sandbox game code as it is right now. There isn't any zombie drawing since it's commented out but the tiled map draws and the camera can zoom in and out.

![screen shot 2016-02-15 at 8 32 57 am](https://cloud.githubusercontent.com/assets/519592/13054572/5e0b3604-d3bf-11e5-8668-4b796a81650e.jpg)

**Comment by WardBenjamin** [comment]
Huh. Does anyone remember why OSX wasn't a supported platform in the first place?

**Comment by craftworkgames** [comment]
@LithiumToast There's no particular reason I didn't add it to the list. I just hadn't tested it and didn't know anyone had already got it working. Please update the wiki with this new info.

**Comment by craftworkgames** [comment]
I've added a few more pages to the wiki. I plan to do more as time permits. I would appreciate it any help, even if it's just proofreading the new pages.

**Comment by Gixen** [comment]
Since you really, really, really need to get some good documentation going i can help proofread or something. Or you know, just run all text through googledocs =).

**Comment by InfiniteProductions** [comment]
It would be good also to answer some important questions (pronoun = the people who wish to use it, not just me ;) ):
- why should I use MonoGame.Extended ?
- how can it help me ? Can I spare time using it ? (or does the time invested in learning MG.Ext will pay and spare me X times this time ?)
- How do I start ?

I believe you really need a true tutorial, showing every step to make a simple game with MG.Ext, not just install or compile it. The questions above are because there are plenty of frameworks, engines and libraries, what's makes MG.Ext different ? Better for a project or another ?

Don't forget documentation are more than important, especially in the beginning of helpers and this is where many team failed (Silicon Studio with Xenko for example is a good example).

**Comment by LithiumToast** [comment]
Here are some examples existing documentation with different technology / projects which I would consider "good".

- https://code.visualstudio.com/Docs
- https://github.com/libgdx/libgdx/wiki
- https://developer.xamarin.com
- https://developer.apple.com/library/ios/navigation/

I think the first thing people should see when they come to documentation is a visibly clear and easy way to navigate the documentation so they can find the help or information they are see seeking. For example a tree of high-level subject areas which can be further navigated into for specific topics of information. A search bar could also be nice to find a specific topic quickly, if it's at all possible with GitHub.

Should we continue using the wiki area for documentation? Or should we look into using [GitHub pages](https://pages.github.com) for having more freedom for displaying the documentation? I think the wiki area on GitHub projects is somewhat constrained in the layout of which documentation can be displayed. For example, it would be nice to have a search bar to quickly find specific information or pages, or the ability to have a custom side or navigation bar.

**Comment by LithiumToast** [comment]
Here are some examples existing documentation with different technology / projects which I would consider "good".

- https://code.visualstudio.com/Docs
- https://github.com/libgdx/libgdx/wiki
- https://developer.xamarin.com
- https://developer.apple.com/library/ios/navigation/

I think the first thing people should see when they come to documentation is a visibly clear and easy way to navigate the documentation so they can find the help or information they are see seeking. For example a tree of high-level subject areas which can be further navigated into for specific topics of information. A search bar could also be nice to find a specific topic quickly, if it's at all possible with GitHub.

Should we continue using the wiki area for documentation? Or should we look into using [GitHub pages](https://pages.github.com) for having more freedom for displaying the documentation? I think the wiki area on GitHub projects is somewhat constrained in the layout of which documentation can be displayed. For example, it would be nice to have a search bar to quickly find specific information or pages, or the ability to have a custom side or navigation bar.

**Comment by craftworkgames** [comment]
> For example a tree of high-level subject areas

This is probably a good place to start. Let's list the subject areas.

> Should we continue using the wiki area for documentation? Or should we look into using GitHub pages for having more freedom for displaying the documentation?

There's pros and cons of using the wiki vs github pages. For now let's just use the wiki. We can always move it if it makes sense later. At this stage, we don't even know what our requirements are so making any decision like this could be wrong. 

One obvious benefit of using the wiki is that it's super easy for anyone to edit. That's what we need right now while we are getting started. Once the documentation takes shape it might make sense to move it.

**Comment by LithiumToast** [comment]
Alternatively, it would be great if GitHub pages displayed the same content as the Wiki but with some modern html / css love for styling the content.

It turns out GitHub wiki is actually [more flexible](https://help.github.com/articles/about-github-wikis/) than I original thought.

@craftworkgames You can add a custom sidebar or footer to pages since you are the owner I think.

**Comment by LithiumToast** [comment]
Also, it seems GitHub has updated their WYSIWYG editor for the wiki; AnsiiDoc is a visible option to select from for markup style and even has a quick reference for each markup style right in the editor.

**Comment by craftworkgames** [comment]
Yes I can update the sidebar. 

On a related note, we'll probably generate API docs with the build system at some point #108. I figured they would be hosted on github pages perhaps.

**Comment by LithiumToast** [comment]
So where's the line in the sand between the documentation to be created on the wiki and the documentation that will be automatically generated for the API? Should the API documentation have an area for code examples and discussion on best practices to use the API?

**Comment by craftworkgames** [comment]
> So where's the line in the sand between the documentation to be created on the wiki and the documentation that will be automatically generated for the API?

Typically documentation on a wiki is quite different to API documentation. 

Wiki documentation usually consists of Tutorials, Guides, Getting Started stuff, Installation instructions, Setting up Dev Environments, Tools, How To's, Examples, etc.  In other words, this is the kind of documentation that's very much hand written.

API documentation is usually just the XML comments that define the public API of the classes, methods and properties of the library.

> Should the API documentation have an area for code examples and discussion on best practices to use the API?

It really depends on what the API doc generation tool provides. Having simple examples to demonstrate using the API makes sense but I wouldn't write detailed tutorials in the API docs.

**Comment by xnamahx** [comment]
Just added a small tutorial for sprite animations. Hopes its clear and if its fine i`ll be glad to collaborate more.

**Comment by craftworkgames** [comment]
@xnamahx Hey, sorry I've only just got around to replying to this. I think tutorials like this are absolutely fantastic, thanks so much 😄 

Here's the link for anyone who can't find it 😉 https://github.com/craftworkgames/MonoGame.Extended/wiki/Animated-Sprites

I was actually experimenting a couple of weeks ago with moving the documentation to [github pages](http://craftworkgames.github.io/MonoGame.Extended/) instead.

The way it works is that you just add markdown files to the [Docs](https://github.com/craftworkgames/MonoGame.Extended/tree/develop/Docs) folder in the main repo and then we can automate the docs website generation on each build.

But tbh, I'm not sure what's better. On one hand the mkdocs / github pages approach produces a nicer website but on the other it might increase the barrier to entry. What do you think?

**Comment by Temeez** [comment]
Personally I like the github pages method a lot more. The github pages installation page was instantly a lot more readable (imo.) when comparing with the installation wiki page. Documentation being in the Docs folder would also mean that you get the documention alongside the source code, which is nice.

As for the barrier to entry. I think that greatly depends on the person, because I would have easier time with .md files and folders than github wiki. 😄
