### ISSUE TITLE
New potentiel feature: grid library

### ISSUE THREAD

**Issue by InfiniteProductions** [craftworkgames/MonoGame.Extended#134]
As [Dylan suggest](http://community.monogame.net/t/please-introduce-yourself/6818/3), I create this issue to talk about my work on a grid library.

It has been designed initially for rendering random mazes with base layout (to shape it, having maze not only boringly rectangular mostly). It helps drawing a grid on screen with any sizes, as all is fully customizable, cell size are automatically adjusted according to target grid size.

I is suitable for a large set of games: from classic board game (chess, checker, reversi) to puzzle game like Puzznic, Ishido, Sokoban, ...
It only works for "in-cell" game, so Go style game won't work with it, this could be implemented later.
It also only manage window/screen board size, no scrolling/camera is included.

The project is [there](https://github.com/InfiniteProductions/MazeLibrary), there is still a good deal of work to do on it to make make it right for a release, as it has started to be just a helper for the maze project. You may look at the Tic Tac Toe example I made just to show its capabilities, you'll be amazed by how it is easy, as it also automagically handle texture resizing for display.

**Comment by LithiumToast** [comment]
@InfiniteProductions First off welcome! 
I downloaded the project and hacked it together to run on Mac.

Here are some of my results:

<img width="512" alt="screen shot 2016-03-08 at 5 19 05 pm" src="https://cloud.githubusercontent.com/assets/519592/13622200/f1504d34-e551-11e5-9b2e-3d28598985ee.png">

<img width="512" alt="screen shot 2016-03-08 at 5 26 07 pm" src="https://cloud.githubusercontent.com/assets/519592/13622345/ecfee474-e552-11e5-8d1f-5a9a8ec71f6f.png">

Unfortunately MonoGame.Extended already has developed support for [Tiled](http://www.mapeditor.org) for creating tile type games.

One area that is not developed yet is a interactive editor for Tiled running inside a running game or how to generate maps using code, a.k.a. [procedural generation](https://en.wikipedia.org/wiki/Procedural_generation).

**Comment by InfiniteProductions** [comment]
I don't think so, because "two last hope are better than one" :).
And IMHO a tile management system may not be the same as what I've made, unless it is very flexible, you can't usually decide or choose the tile size for example.

But what is very unfortunate is you haven't add a PR for your "hack".

Regarding in-game map editor, it's a very bad idea, considering how XNA/MG handles input, without mentioning file management, using 'Tiled' would be a lot more better.

For the procedural map generation, there is a [good article](http://www.indiedb.com/features/procedural-world-in-machiavillain), and also SharpNoise (a C# port of libNoise), I have convert libNoise tutorials and one procedural texture generation (wood) in [this article](https://infiniteproductionsblog.wordpress.com/2016/02/21/playing-with-libnoise-in-c/).

**Comment by craftworkgames** [comment]
I always figured we'd have a few different ways to create maps in the library. That's why the Tiled code lives in a `Maps.Tiled` namespace. Leaving room for `Maps.SomethingElse` in the future.

That said, I'd much rather have one complete and polished way to create tile based maps over two kinda of working but half broken ways. 

If someone is particularly keen to add this to the library I'm more than happy to create a feature branch to work on it outside the `develop` branch and once it's ready to pull into the main branch we'll do it. It doesn't have to be perfect, but I'd expect it to fit nicely with the rest of the library.

I'm also particularly interested in procedural map generation as a feature. I think that would be different enough that it would sit nicely beside Tiled without being too similar.

Personally I'm a bit overwhelmed at the moment with the amount of things I'm working on with the project. Not just code stuff but handling everything else around the project takes a lot of time. So I won't be getting around to adding this myself anytime soon. I'm more than happy to discuss it though.

**Comment by LithiumToast** [comment]
@InfiniteProductions

> you can't usually decide or choose the tile size for example

With Tiled you can choose the tile size for each map. That's why I think re-inventing the wheel here is not such a great idea.

> But what is very unfortunate is you haven't add a PR for your "hack"

I could but I'm using MonoGame 3.5, which is not officially released yet. Things could change from now and when 3.5 is released, potentially breaking things. I'm not really interested in maintaining a pull request outside of MonoGame.Extended, sorry. I could create a fork and commit and push to that if you want though.

> Regarding in-game map editor, it's a very bad idea, considering how XNA/MG handles input, without mentioning file management, using 'Tiled' would be a lot more better.

Yes it's more work, but there are some benefits to having at least an object placement editor running inside the game. For the Tiled map editor, objects are just drawn as a rectangle outline; there are no sprites or other assets for representing the objects. This can make editing maps cumbersome when placing or editing objects as the game developer would have to edit the map in Tiled, re-compile the map with the content pipeline and then load up the game just to confirm object edit or placement was correct. Having a "in-game" editor, somewhat to what you have going already, could be beneficial.

> For the procedural map generation, there is a good article, and also SharpNoise (a C# port of libNoise), I have convert libNoise tutorials and one procedural texture generation (wood) in this article.

Interesting. This is definitely something useful for certain games, at least in my opinion. We can talk about it if you want but I too am pretty overwhelmed with my commitments to MonoGame.Extended already like `PrimitiveBatch`, collision detection, and collision response.

**Comment by craftworkgames** [comment]
Not enough interest in this feature at this point in time.
