### ISSUE TITLE
Shapes rework

### ISSUE THREAD

**Issue by ExCellRaD** [craftworkgames/MonoGame.Extended#165]
Because shapes are a big core feature in a 2D library, the shapes functionality is going to need  to be expanded.
Let's discuss what to add/change:

- Make shapes classes or keep them as structs
- What methods and properties should be implemented in IShapeF
- Curves and lines implementation
- New interfaces for different shapes such as curves
- Polygon with curve sides
- Changes to exisisting shapes

**Comment by ExCellRaD** [comment]
For the particle work I'm doing, I think it would be better to have shapes as classes than as structs. Main reason would be that I'm using interfaces to determine which shapes can be used and structs will box them. The reason why the shapes are structs right now is probably because `Rectangle` in monogame is a struct (I'm guessing), but these shapes are going to contain a lot more functinality than `Rectangle`.

About adding things to `IShapeF`, I think we should add everything that gets used in the framework, such as drawing, random points for particles, getting the mesh, collisions so that if someone makes a new shape, they can use it for everything the other shapes are getting used for.

**Comment by LithiumToast** [comment]
>reason would be that I'm using interfaces to determine which shapes can be used and structs will box them

Boxing can be avoided for structs which implement an interface by using generics on a method or class. For example, consider `IVertexType` and `GraphicsDevice.DrawUserPrimitives()`:

```public void DrawUserPrimitives<T>(PrimitiveType primitiveType, T[] vertexData, int vertexOffset, int primitiveCount) 
where T : struct, IVertexType```

See on simple answer here: https://social.msdn.microsoft.com/Forums/en-US/359cf58a-f53d-478e-bc31-1507e77c9454/is-there-boxing-when-generic-classes-get-structs-with-interface-constraint-?forum=csharplanguage

And from, [Generic Interfaces (C# Programming Guide)](https://msdn.microsoft.com/en-us/library/kwtft8ak.aspx):
>The preference for generic classes is to use generic interfaces, such as IComparable<T> rather than IComparable, in order to avoid boxing and unboxing operations on value types.

> but these shapes are going to contain a lot more functinality than Rectangle.

It's not about more or less functionality when thinking about struct vs class. It's about whether we want the memory to be on the stack as a value type (or within the memory for another type directly) or on the heap as a reference type. See [Six important .NET concepts: Stack, heap, value types, reference types, boxing, and unboxing](http://www.codeproject.com/Articles/76153/Six-important-NET-concepts-Stack-heap-value-types) for rundown on stack vs heap.

Implicit shapes should probably be structs. These are: rectangles, circles, spheres, cubes, cones, cylinders, ellipsoids, tori, and other geometric primitives that are not explicitly defined by vertices but implicitly though a mathematical expression. Implicit geometry can be described as a function mapping from 2D or 3D space to real numbers, `F: R^2 -> R` for 2D and `F: R^3 -> R` for 3D where the points given by `f(x, y) < 0` (2D) or `f(x, y, z) < 0` (3D) constitute the interior, `f(x, y, z) = 0` or `f(x, y, z) = 0` the boundary, and `f(x, y) > 0` or `f(x, y, z) > 0` the exterior. For example a circle, has the equation `x^2 + y^2 = r^2` and a sphere `x^2 + y^2 + z^2 = r^2` for the boundary. So a circle needs a `Vector2` for centre position, and a `float` for radius. A sphere needs a `Vector3` for centre position and a `float` for radius. Both these examples require a small amount of memory to define the shape which is why a `struct` would be preferable. I will use implicit shapes for collision bounding volumes for quickly check if two objects are possible colliding, and if they are, use a more expensive but detailed analysis of their explicit collision shapes for collision response. (Though maybe for some simple games, implicit shape collision detection might be good enough.) 

Explicit shapes should probably be classes. These are any shapes which are defined by a mesh of vertices such as a 3D model. See [Polygon Mesh](https://en.wikipedia.org/wiki/Polygon_mesh). They also might have different representations for different needs and algorithms. For example, a [vertex-vertex mesh](https://en.wikipedia.org/wiki/Polygon_mesh#Vertex-vertex_meshes) might created by a user or algorithm ([convex hull algorithm](https://en.wikipedia.org/wiki/Convex_hull_algorithms) for example) and it needs to to converted to a [face-vertex mesh](https://en.wikipedia.org/wiki/Polygon_mesh#Face-vertex_meshes) to be drawn correctly by the graphics hardware.

I also propose the following:

```
    public interface IExplicitShape
    {
        IImplicitShape GetBoundingVolume();
    }

    public interface IImplicitShape
    {
        float Left { get; }
        float Top { get; }
        float Right { get; }
        float Bottom { get; }
        float Front { get; }
        float Back { get; }

        bool Contains(Vector3 point);
        bool Intersects(IImplicitShape other);
    }
```

**Comment by ExCellRaD** [comment]
I agree with your points on why something should be a struct, but the way they are going to be used still makes me think they are more fit to be classes.

> Boxing can be avoided for structs which implement an interface by using generics

This would mean that a class can't contain members of `IShapeF `which can be changed to another shape (of a different kind) at runtime. You also have to create interfaces for those classes so you could be able to have them be members of other classes/ making arrays of them.
example: `List<Class<Type>>` can't contain `IShapeF` classes of different kinds
When we are going to implement the entity system, the collision mesh component will probably contain an array of `IShapeF `objects, we can't expect them to all be the same type and we probably don't want to box them. Same reasoning goes with the particle rework where you would want a spawner or container to be changed to a different shape at runtime.

> It's not about more or less functionality when thinking about struct vs class.

Exactly, but it's about which functionality though (using them as a `IShapeF` in a lot of cases instead of their type directly)

> Explicit shapes should probably be classes.

Agreed, but wouldn't it be more clear to call them meshes? just so they wouldn't get confused with the current (implicit) shapes.

**Comment by LithiumToast** [comment]
> his would mean that a class can't contain members of IShapeF which can be changed to another shape (of a different kind) at runtime.

Yup. If you have a `Circle`, you can't morph it into a `Rectangle`. They have different mathematical definitions for testing interior, boundary and exterior. They can both implement a common interface though. That's the current `IShapeF`. A class could do something like this for strongly typing the shape

```
public class MyObject<TShape> where TShape : IShapeF
{
}
```
Or do something like this for changing the shape at runtime:

```
public class MyObject
{
    public IShapeF Shape { get; set; }
}
```
The latter would box the shape if it was a struct however. Boxing is fine as long as it's boxed once and not consistently every frame.

> You also have to create interfaces for those classes so you could be able to have them be members of other classes/ making arrays of them.

I don't understand what you are saying? Struct, class, interface, doesn't matter. They can all be members of each other when writing code for the type. You can also create an array of shapes using the interface.

```
var shapes = new IShapeF[] { new CircleF(), new RectangleF() };
```

This array is a collection of references though since each element has to casted to the interface type (boxed) since interfaces can only be objects unless constrained through a generic on a method or class like I showed earlier.

>When we are going to implement the entity system, the collision mesh component will probably contain an array of IShapeF objects

There will be a [bounding volume](https://en.wikipedia.org/wiki/Bounding_volume) shape (the proposed `IImplicitShape`), and a collision shape (the proposed `IExplicitShape`). The bounding volume shape completely contains the collision shape and is meant for quickly checking if two entities don't collide. This is because checking whether two implicit shapes collide is way faster than checking if two explicit shapes collide. For example checking whether two rectangles collide is trivial; just a simple mathematical equation to solve. Checking whether two polygons collide is not so trivial and requires [linear algebra](https://en.wikipedia.org/wiki/Linear_algebra) to use the [separating axis theorem](https://en.wikipedia.org/wiki/Hyperplane_separation_theorem).

The collision object will contain a set of bounding volume and collision shape pairs that make up the collision object. Then using [constructive solid geometry (CSG)](https://en.wikipedia.org/wiki/Constructive_solid_geometry) a bounding volume hierarchy can be created using the sum of the bounding volumes. Each node of the bounding volume hierarchy will have the explicit collision geometry (the polygon mesh) for that bounding volume to use for the more expensive [separating axis theorem](https://en.wikipedia.org/wiki/Hyperplane_separation_theorem) collision detection algorithm. The polygon meshes might have to "combined" if they overlap; see [convex hull](https://en.wikipedia.org/wiki/Convex_hull).

>but it's about which functionality though (using them as a IShapeF in a lot of cases instead of their type directly)

That's what generics are for; methods or classes which need any type of `IShapeF` can constraint the interface like I showed earlier and the advantage is they don't get boxed if they are structs.

>but wouldn't it be more clear to call them meshes? just so they wouldn't get confused with the current (implicit) shapes.

Maybe? `Polygon` and `Polyhedra` are shapes. Wouldn't make sense to have those exist and a `VertexMesh` class; both of them are essentially the same thing.

**Comment by ExCellRaD** [comment]
> Maybe? Polygon and Polyhedra are shapes. Wouldn't make sense to have those exist and a VertexMesh class; both of them are essentially the same thing.

It would have limited functionality (only for drawing purposes) compared to the current `PolygonF`. It would allow you to change the position and the texture position (and color) of individual vertices without having an implicit shape to change. 

Coming back to the struct vs class:

> `var shapes = new IShapeF[] { new CircleF(), new RectangleF() };`

Doing stuff like this will box the objects and thus remove references to the original object. Having them be classes would mean you can change the shape even while it is in the array (or as any other `IShapeF `reference). With them being structs you would either have to remake the array or keep an integer that references the position of the element in the array. 
Boxing is also bad for performance, it's a lot more heavy than getting the values of the heap. 

An example using structs:
We have some kind of circle entity, using a shape visual component to render the circle (stores a boxed copy of the circle as an `IShapeF`), we have a collision component (stores another boxed `IShapeF`)
and we have a particle spawner on the edge of the circle (yet another boxed copy). Now we want to change the radius of the circle (and all of the components with it): 
Struct way: We make a new `CircleF` with the new radius and set it to all of the members of the components (which requires boxing again, and requires you to know which components need to be updated). Doing this every frame for multiple shapes will definitely have a performance hit.
Class way: We change the radius on the circle object we already have, nothing else.

Another benefit is inheritance (someone using MG.E should have the option to add functionality to shapes).

**Comment by LithiumToast** [comment]
> Doing stuff like this will box the objects

Yes.

>thus remove references to the original object

???. The struct is boxed. Structs are not references... I would highly recommend you read the [Six important .NET concepts: Stack, heap, value types, reference types, boxing, and unboxing](http://www.codeproject.com/Articles/76153/Six-important-NET-concepts-Stack-heap-value-types) for clarification.

> Having them be classes would mean you can change the shape even while it is in the array (or as any other IShapeFreference)

Same goes for the boxed struct if you use `IShapeF` as the variable type. Honestly I think leaving them as structs is fine and is consistent with the existing `Rectangle`. People are already expecting the implicit shapes to be structs from their XNA experience.

>With them being structs you would either have to remake the array or keep an integer that references the position of the element in the array. 

That's why constrained generics are a thing.

```
void MyMethod<T>() where T : struct, IShapeF
{
var shapes = new T[] { new CircleF(), new RectangleF() };
}
```

>Boxing is also bad for performance, it's a lot more heavy than getting the values of the heap.

A lot more "heavy" on performance? What does even mean? And from instead of getting the values from the heap? What? References exist on the heap... Values exist on the stack... When you box a struct (value on the stack) into a object (reference on the heap) a new object is created... This problematic if it's being done constantly every frame. Doing it once or twice is not the end of the world.

>We have some kind of circle entity, using a shape visual component to render the circle 

Rendering the circle requires a polygon mesh. These shapes as they currently exist are not meant for rendering. They are meant for algorithms and pieces of code to consume.

>Class way: We change the radius on the circle object we already have, nothing else.

Ok I understand what's going on now. 

Approach 1: Use a generic parameter for `IShapeF` to create or update a polygon mesh representation of that shape. The particle emitter can then use that explicit shape to emit particles. 

Approach 2: Make `Profile` take a generic parameter of type `IShapeF`. Create a new `Profile<TShape>` every time you need to change the type of shape for the particle emitter. The shape can be directly accessed without boxing and even change it's values such as a circle's radius if we allow the struct to be mutable.

Approach 3: Use constructive solid geometry to create an implicit shape of volume where the particle will possibly end up. i.e. if `f(x, y, z) <= 0` for inside or on the boundary of the composed implicit shape.
There would only be one `Profile` object for the constructive solid geometry. `IShapeF` items could be added to the hierarchy tree without boxing using a generic method. When the solid geometry changes create a new convex hull polygon mesh. Use that explicit shape (the polygon mesh) to specify the area for particles to emit from randomly.

**Comment by ExCellRaD** [comment]
I see that it's possible, and I have no problem implementing it using structs. But having to do all this work (generic parameter stuff / converting every shape into a polygon representation first) IS a lot more work, and has to be repeated for every feature that uses the shapes. Not only is it harder to implement, it's also less performant and less obvious to work with (people mainly using classes, and knowing how to work with those).

I'm going to list the cons (disadvantages?) of both approaches:
struct:
- less performant in a lot of cases due to generic implementations or boxing.
- requires you to have knowledge of boxing, stack vs heap, generic parameters if you want to create a feature using it.
- generic parameter approaches makes you lose functionality (`List<Profile<TShape>> `vs `List<Profile>` which could hold any shape) which can be avoided, but again with a lot of work and knowledge of how to do it.
- no references possible, means more work to update existing objects instead of one.
- no inheritance.

class
- slower in use cases where you only create it to pass as argument (I agree it's bad for that, but as I've said many times before, the functionality of the shapes goes far beyond this)
- "People are already expecting the implicit shapes to be structs from their XNA experience."
- "They don't use enough memory to be classes"

**Comment by LithiumToast** [comment]
> it's also less performant and less obvious to work with

I disagree. Structs used appropriately can reduce memory (not creating a new object every time you need to have a circle). Array of structs is as low overhead as we can get and would benefit for [CPU cache coherence](https://en.wikipedia.org/wiki/Cache_coherence).

>less performant in a lot of cases due to generic implementations or boxing.
I'll say it again.. Generics **prevent** boxing of structs. This means it **increases** performance, especially if the code runs often like every frame or so.

>requires you to have knowledge of boxing, stack vs heap, generic parameters if you want to create a feature using it.
People can just use the code once it's finished... No knowledge of stack vs heap or boxing required. Sure they have to understand how to use the API with a generic but whatever; the API is what it is.

>generic parameter approaches makes you lose functionality (List<Profile<TShape>>vs List<Profile>
Then have a `IProfile` interface which defines what is needed for the particle emitter.

>no references possible, means more work to update existing objects instead of one.
???.

>no inheritance.

That' a good thing. I don't want `CircleF` to inherit from `RectangleF`. Inheritance is not always the greatest. Having monolithic objects has it's own negative consequences. If two structs need to share a similar API that's exactly what interfaces are for; in-fact that's exactly what `IShapeF` is doing right now.

> slower in use cases where you only create it to pass as argument 

It's actually pretty fast to instantiate objects... The problem is a new object lives on the heap. Doing this every frame and ~uh-oh there is a lot of garbage being created; potentially a memory leak if the objects have uncleared references preventing garbage collector from freeing the memory.

>"People are already expecting the implicit shapes to be structs from their XNA experience."

Take a look at [Rectangle source code on MonoGame](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Rectangle.cs). 

```
/// <summary>
    /// Describes a 2D-rectangle. 
    /// </summary>
    [DataContract]
    [DebuggerDisplay("{DebugDisplayString,nq}")]
    public struct Rectangle : IEquatable<Rectangle>
    {
...
    }
```

People are already use to that `Rectangle` API as a struct. Having a `RectangleF` as a class would confuse a lot of people.

**Comment by ExCellRaD** [comment]
Okay since you seem pretty adamant about using structs, let's keep that (unless @craftworkgames has a different opinion on this?). For now there's no real reason for them being classes yet anyway. We can do some tests later and maybe come back to this then if need be.

Let's get to the other points then. How would we go about getting the explicit shapes from the current implicit ones? What methods need to be added for collision?

The methods that are needed for particle rework are: 
- getting a random point inside (only on shapes with area)
- getting a point on the outline (all shapes and paths)

About the lines/curves: Does the line implement `CurveF `(which means it becomes a class) or do they share a common interface `IPathF`. this interface could be used to spawn particles from, the same way as the outline of a shape which could create some really cool stuff. We could later implement a system that uses paths to animate objects to, this would require a path class composed of `IPathF `segments. We should also look into creating a shape this way (closed polygon with `IPathF `sides). 

Currently I have these curves:
- N-point bezier
- cubic bezier (faster algorithm than the N-point one)
- quadratic bezier (an even faster algorithm)
- Arc (desribes a part of a circle, defined by three points)
- LineF, default straight line

Is there need for more? perhaps catmull?

**Comment by craftworkgames** [comment]
I agree with @LithiumToast on this one. They should stay structs.

> Does the line implement CurveF(which means it becomes a class) or do they share a common interface IPathF

We don't really gain a lot by deriving from a base class so let's stick with the interface. These shapes are supposed to be fairly lightweight which means building a deep inheritance hierarchy is the opposite.

> getting a random point inside (only on shapes with area)

Speaking of random, we should probably pull the fast random implementation out of the particles namespace and move it to the root namespace.

**Comment by craftworkgames** [comment]
Oh yeah, I was going to mention before. We should really look at the shapes in farseer physics

**Comment by LithiumToast** [comment]
@ExCellRaD 

> How would we go about getting the explicit shapes from the current implicit ones?

To go from a `RectangleF` or `CircleF` to a polygon mesh is just creating a new array of vertices and setting the position of each vertex (and maybe each normal) using some math. Nothing crazy.

> About the lines/curves:

Curves should probably be their own thing. I don't know if curves should implement an `IPath` interface. What would that interface expose exactly?

**Comment by ExCellRaD** [comment]
> To go from a RectangleF or CircleF to a polygon mesh is just creating a new array of vertices and setting the position of each vertex (and maybe each normal) using some math. Nothing crazy.

Would that be a method `GetMesh() `defined in `IShapeF`? What about Texture coordinates?

> What would that interface expose exactly?

`StartPoint`, `EndPoint `and `GetPointOnCurve(float t)`. This would allow us to make a combined path of multiple `IPathF `segments, and also a `IShapeF `with sides that are IPaths. The purpose is to keep the `LineF` a struct and not a class, but still being able to use it as one of these segments.

**Comment by craftworkgames** [comment]
>  I think we should add everything that gets used in the framework, such as drawing

I'm just reading through this discussion and I noticed this one. Let's just be clear on this because I'm not exactly sure what you had in mind. Adding a `Draw` method to the `IShapeF` interface is not a great idea. It would couple the implementation of shapes to *one way* of drawing it (i.e. with a `SpriteBatch` for example).

The way around this is to use extension methods as we've [already done](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Shapes/SpriteBatchExtensions.cs). I'll admit, the implementation of these is not great but it's a start. In future I'd like to see a few different ways of drawing shapes, maybe using `PrimitiveBatch` instead.

**Comment by LithiumToast** [comment]
@ExCellRaD 

>Would that be a method GetMesh()defined in IShapeF? What about Texture coordinates?

I really do not want to bloat an interface with a whole bunch of stuff that is used uncommonly. A extension method like @craftworkgames  mentioned is probably the cleanest way do it.

>StartPoint, EndPoint

That's fine.

> GetPointOnCurve(float t)

Uh, a line or a way point has a implement a method called `GetPointOnCurve(float t)` to be an `IPath`? A line is not a curve. I think keeping a `Curve` and a `Path` class seperate like farseer physics does it is probably the easiest.

@craftworkgames 

Yes. The shapes need to be converted a face-vertex polygon mesh which then can be used with `PrimitiveBatch` for rendering. Those vertices need somewhere to hang out in memory; either in a new object which is my proposal of the `IExplicitShape` interface, or, the vertices could generated on the fly and copied into `PrimitiveBatch`'s buffer.

**Comment by ExCellRaD** [comment]
@LithiumToast 
So for the getting the mesh there would be a method (for each shape) that returns the explicit shape defined by vertices which only contain position data:

``` cs
public static IExplicitShape<TVertex> GetMesh<TVertex>(this Shape shape) 
   where TVertex: struct, IVertexType, IMovable
```
The explicit shape would have an array of `TVertex`.
Vertices would need to be defined like this:
``` cs
public struct Vertex2D : IVertexType, IMovable
{
   public Vector2 Position {get;set;}
   ...
}
```

we can now create and set positions of the vertices without knowing what type it is

does this seem like a good way to go?

**Comment by LithiumToast** [comment]
>Vertices would need to be defined like this:

`VertexPositionColor`, `VertexPositionColorTexture`, `VertexPositionNormal`, etc, already exist...

```
public static TMesh CreateMeshFromShape<TMesh, TMeshVertexType, TShape>() where TMesh : IMesh<TMeshVertexType> where TMeshVertexType : struct, IVertexType where TShape : struct, IShapeF
    {
        /// fill in the vertices with the correct position from the shape
        /// using the appropriate order for vertices and indices from the mesh type
    }

public interface IMesh<TVertexType>
        where TVertexType : struct, IVertexType
    {
        IReadOnlyCollection<TVertexType> Vertices { get; }
        IReadOnlyCollection<short> Indices { get; }
    }

public class FaceVertexMesh<TVertexType> : IMesh<TVertexType>
        where TVertexType : struct, IVertexType
    {
        private TVertexType[] _vertices;
        private short[] _indices;

        public IReadOnlyCollection<TVertexType> Vertices
        {
            get { return _vertices; }
        }

        public IReadOnlyCollection<short> Indices
        {
            get { return _indices; }
        }

        public PrimitiveType PrimitiveType { get; }

        public FaceVertexMesh(PrimitiveType primitiveType, TVertexType[] vertices, short[] indices = null)
        {
            if (vertices == null)
            {
                throw new ArgumentNullException(nameof(vertices));
            }

            PrimitiveType = primitiveType;
            _vertices = vertices;
            _indices = indices;
        }

        public void Draw(PrimitiveBatch<TVertexType> primitiveBatch, IDrawContext drawContext = null)
        {
            if (_indices != null)
            {
                primitiveBatch.Draw(PrimitiveType, _vertices, _indices, drawContext);
            }
            else
            {
                primitiveBatch.Draw(PrimitiveType, _vertices, drawContext);
            }
        }

        public void Draw(PrimitiveBatch<TVertexType> primitiveBatch, int startVertex, int vertexCount, IDrawContext drawContext = null)
        {
            primitiveBatch.Draw(PrimitiveType, _vertices, startVertex, vertexCount, drawContext);
        }

        public void Draw(PrimitiveBatch<TVertexType> primitiveBatch, int startVertex, int vertexCount, int startIndex, int indexCount, IDrawContext drawContext = null)
        {
            primitiveBatch.Draw(PrimitiveType, _vertices, startVertex, vertexCount, _indices, startIndex, indexCount, drawContext);
        }
    }
```
