### ISSUE TITLE
Matrix2D

### ISSUE THREAD

**Issue by ExCellRaD** [craftworkgames/MonoGame.Extended#186]
Proposal for a more efficient and 2D focused matrix struct.

The implementation would have 6 float fields compared to `Matrix`'s 16 which would allow much faster multiplications of matrices (20 float operations instead of 112). Other operations will be a lot faster too, but multiplication being the important one.
There would be property accessors for `Position`, `Scale `and `Rotation` which makes it a lot easier for people to understand without matrix math knowledge.
There would be a lot less overhead, keeping only 2D methods. Naming would also match better (`CreateRotation() `instead of `CreateRotationZ()`).
No more unnecessary casts to and from Vector3 for scale and translation, same with quaternion.
More specific 2D methods without the need for extension methods such as `Shear`.

I already have this working, and I could submit a PR if you're interested. I would need to make a lot of unit tests first though.

**Comment by LithiumToast** [comment]
A 2D game is really just a 3D game with a specific perspective called [orthogonal projection](https://en.wikipedia.org/wiki/Orthographic_projection). In this type of projection the Z axis can be used a layering technique, and that's exactly how `SpriteBatch` works for depth.

(unsafe context code snippet)
```
positionColorTexturePointer->Position.Z = spriteInfoPointer->Depth;
```

>The implementation would have 6 float fields compared to Matrix's 16 which would allow much faster multiplications of matrices (20 float operations instead of 112). Other operations will be a lot faster too, but multiplication being the important one.

The compiler should be using the [SIMD](https://en.wikipedia.org/wiki/SIMD) for `Matrix` operations so there could be a performance gain, but I don't know if it will be as huge of difference as you may think. Passing a `struct` by reference using the `ref` keyboard also allows the CPU to copy a "pointer" (4 bytes on x86, 8 bytes on x64) instead of the whole 16 floats (64 bytes) of the `Matrix`.

>There would be property accessors for Position, Scaleand Rotation which makes it a lot easier for people to understand without matrix math knowledge.

Properties in C# are really just methods and should be avoided in performance critical areas. The just-in-time or ahead-of-time compiler might inline methods but we don't have strict control over that. The convention for the translation (position) stored in the `Matrix` is in `M41`, `M42`, `M43` for XNA / MonoGame. Infact MonoGame already has the `Translation` property on `Matrix`:

```
public Vector3 Translation
        {
            get
            {
                return new Vector3(this.M41, this.M42, this.M43);
            }
            set
            {
                this.M41 = value.X;
                this.M42 = value.Y;
                this.M43 = value.Z;
            }
        }
```

As you can see there is very little overhead involved with returned one extra float compared to a 2D version. It's a similar story for `Scale` and `Rotation`, but `Rotation` is a [quaternion](https://en.wikipedia.org/wiki/Quaternion). 

>No more unnecessary casts to and from Vector3 for scale and translation, same with quaternion.
`Vector2`, `Vector3`, and `Quaternion` are value types; they are `struct`s. It is very cheap to create a new `Vector3` on the stack with the `Vector2` values and vice versa. If it only needs to be done once or twice per frame it's not a big deal.

The point is learning about vectors and matrices from linear algebra is fundamental knowledge for game development. I would rather leave the `Matrix` as it is and have a 2D API for drawing which hides the details of the linear algebra completely; I think that's why `SpriteBatch` is so popular.

**Comment by ExCellRaD** [comment]
> I would rather leave the Matrix as it is and have a 2D API for drawing which hides the details of the linear algebra completely; I think that's why SpriteBatch is so popular.

Agreed, `Matrix` is still needed for drawing purposes. A `Matrix2D` will still need to be cast to a `Matrix` for using in effects. This would still be far more efficient than using `Matrix` objects the whole way through though.
The main purpose of this struct would be for 2D transformations, and applying those to meshes for example. This would be faster, require less memory, be easier to understand and easier to implement than using the current `Matrix` which is meant to be used for 3D calculations. 
> As you can see there is very little overhead involved

We can do better and remove the overhead completely. Having it return a Vector2 is so much better in every single way. 

I'm not saying the current `Matrix` implementation is bad or not useful, because it really isn't. There are just so many optimizations that can be done when working in 2D space that I think `Matrix2D` would be very handy in this framework. Also having some extra methods for 2D makes this very appealing.

**Comment by ExCellRaD** [comment]
> Passing a struct by reference using the ref keyboard also allows the CPU to copy a "pointer" (4 bytes on x86, 8 bytes on x64) instead of the whole 16 floats (64 bytes) of the Matrix.

Typo there (keyword). Does the 'out' parameter keyword work the same way btw?

**Comment by LithiumToast** [comment]
>The main purpose of this struct would be for 2D transformations, and applying those to meshes for example. This would be faster, require less memory, be easier to understand and easier to implement than using the current Matrix which is meant to be used for 3D calculations.

Well the problem is matrix multiplication is only going to work with square matrices or mutual sizes of row to column and column to row. You can't multiply a 3x2 matrix with a 3x2 matrix. But you can multiply a 3x3 matrix with a 3x3 matrix and a 3x2 matrix with a 2x3 matrix. So I think calling it `Matrix2D` is confusing.

> We can do better and remove the overhead completely. Having it return a Vector2 is so much better in every single way.

Did you profile? I doubt you are going to see much overhead difference if any at all... If you want to have it return a `Vector2` you could have an extension or helper method for `Matrix`. Something like,

```
public static class MatrixHelper
{
    public static Vector2 GetTranslation2D(ref Matrix matrix)
    {
        return new Vector2(matrix.M41, matrix.M42);
    }
}
```
> There are just so many optimizations that can be done when working in 2D space

Every optimization claim with C# code needs profiling. There is a LOT going on with the C# language to get it to run on a specific machine.

> Typo there (keyword). Does the 'out' parameter keyword work the same way btw?

`ref` and `out` keyboards assed to parameters causes the parameters to be passed by reference.

**Comment by LithiumToast** [comment]
There could even be general extension methods for converting between `Vector3` and `Vector2`.

```
        public static Vector2 ToVector2(this Point point)
        {
            return new Vector2(point.X, point.Y);
        }

        public static Vector2 ToVector2(this Vector3 vector)
        {
            return new Vector2(vector.X, vector.Y);
        }
```

**Comment by craftworkgames** [comment]
> which would allow much faster multiplications of matrices 

1. Are you sure it's faster? Have you profiled it?
2. Have you seen anything like this in any other game framework?
3. How exactly do you think it would be used?
4. What problem are you actually trying to solve here? Is the performance of a `Matrix` really an issue?

Many years of thought have been put into Matrix math used in game engines. I highly doubt we are going to come up with anything ground breaking here.

Frankly, I'm not interested in this kind of stuff in the library unless there's a really clear benefit with actual proof.

**Comment by ExCellRaD** [comment]
You didn't even let me answer? Or leave this open for discussion?

**Comment by LithiumToast** [comment]
His point was that there needs to be proof it's faster via profiling before thinking about this in more detail. This problem does really seem like a waste of time without that proof.

**Comment by ExCellRaD** [comment]
That doesn't mean i can't deliver proof?

**Comment by craftworkgames** [comment]
Just because the issue is closed doesn't mean you can't keep talking. 

Come back with proof an we'll re-open the issue.

I'm just tired of having so many open issues that aren't going anywhere. I'm going to start cleaning them up.

**Comment by ExCellRaD** [comment]
>I'm just tired of having so many open issues that aren't going anywhere.

I understand that, but as I said, I already have this working and I can PR it. It only needs some tests first.

What kind of proof are you talking about, pure performance? How would I best go about doing that?

**Comment by craftworkgames** [comment]
> What kind of proof are you talking about, pure performance? How would I best go about doing that?

That's a good question. To be honest I think it's pretty difficult to answer and that's exactly why I'm not interested in this issue. 

Pure performance is one thing you could measure but it's not the only thing that matters. In fact, I'm not sure it even matters enough to bother wasting time on it. I've never heard anyone complain about the performance of using a `Matrix`.

More importantly, how exactly is this going to help someone making an actual game? What would they have to do to actually use it in the real world? How would they pass it into a sprite batch or use it in a particle system? How would they convert between `Matrix` and `Matrix2D`? Would you loose the performance benefits during the conversion?

Those questions are not easy to answer, but they are important. 

Put yourself in my shoes. What am I supposed to do with your PR? How do I test it? Where's the value?

**Comment by craftworkgames** [comment]
Sorry to beat a dead horse (pun intended) but I just found [this post by Eric Lippert](https://ericlippert.com/2012/12/17/performance-rant/) while I was working on something completely unrelated. It's performance related code and I thought it might be helpful here. It's well worth the read for any programmer.

Here's my favorite bit (although, please read the whole post so this quote isn't out of context):

> Spend your valuable time worrying about something else, like testing, robustness, security, and so on. Unnecessary code changes are expensive and dangerous; don’t make performance-based changes unless you’ve identified a performance problem.

I know we are game programmers and performance is often a concern but unless it's been identified as a problem we have better things to worry about. More testing, documentation, fixing bugs and properly designing useful features are far more important at this stage of the library.

**Comment by LithiumToast** [comment]
@ExCellRaD We added a `Matrix2D` finally anyways when `Transform2D` was added.

**Comment by ExCellRaD** [comment]
Looks very good!

**Comment by craftworkgames** [comment]
> We added a `Matrix2D` finally anyways when `Transform2D` was added.

Did we *need* to create `Matrix2D` to get `Transform2D` working or could it have worked just as well with a `Matrix`?  

I really don't know the answer to the above question. So I trust that it's the right decision. As with anything, I'm sure it's a trade off between the pros and cons. Like, converting between `Matrix2D` and `Matrix` could be a pain, for example. Only time will tell if it's a problem though.

**Comment by LithiumToast** [comment]
> Did we need to create Matrix2D to get Transform2D working or could it have worked just as well with a Matrix?

It could of worked fine with `Matrix`, but it's a waste of memory to have 16 floats for 2D transformations when 6 floats are only needed. That's 40 bytes saved each time `Matrix2D` is used instead of `Matrix`. `Transform2D` has to use 2 matrices so that's 80 bytes saved per `Transform2D` instance.

> converting between Matrix2D and Matrix could be a pain

There exists an implicit operator already so a `Matrix2D` can be passed to any method parameter which takes a `Matrix` already like `SpriteBatch.Begin`.

**Comment by craftworkgames** [comment]
It's always a trade off between memory and CPU.

My concern is that the conversion, implicit or not could outweigh the memory benefits. Of course, it is just copying some floats around so I guess that's not going to be very taxing on the CPU.

**Comment by LithiumToast** [comment]
The conversion to `Matrix` from `Matrix2D` is literally just copying 6 floats into the correct fields. There is no math involved. Copying 24 bytes is hardly anything significant for the CPU.
