### ISSUE TITLE
CollisionWorld and deleting actors

### ISSUE THREAD

**Issue by mustelan** [craftworkgames/MonoGame.Extended#189]
Why has no DeleteActor method in CollisionWorld class? What is the reason of that?

**Comment by craftworkgames** [comment]
No good reason.

CollisionWorld needs a lot of work. More than likely the whole thing is going to be replaced by something else entirely. 

It may even be worth removing it from the library to avoid any more confusion until we've got something better.

**Comment by LithiumToast** [comment]
@mustelan No promises, but I'm progressing towards an extensible collection detection system. I don't know exactly when I will get there since I'm doing this in my free-time / when I feel like it (sometimes the two are mutually exclusive). I do have to get #152 done first though so I can start drawing basic shapes that represent hit boxes, lines and so forth.
