### ISSUE TITLE
Template reference issue

### ISSUE THREAD

**Issue by SoundGoddess** [craftworkgames/MonoGame.Extended#192]
When I install the template as per the instructions here:

https://github.com/craftworkgames/MonoGame.Extended/tree/develop/ProjectTemplates

For some reason the reference is erroring out:

https://hathor.tinytake.com/sf/NjMyMzk5XzMwOTY4MjA

I can run the NuGet update and it fixes it, but I thought I'd mention this anyway.

**Comment by craftworkgames** [comment]
The project template wasn't intended to be used with the NuGet package. It's used to create new demos in the MonoGame.Extended source code like the ones we already have.

However, I can see how the readme could be confusing. Clearly we need better instructions here.

We already have an open issue #106 about creating project templates that are intended to be used with the NuGet package. I'm going to close this issue since it's closely related to that one.

**Comment by SoundGoddess** [comment]
ok I'm happy to help with the documentation

**Comment by craftworkgames** [comment]
I was talking to @LithiumToast this morning about our documentation. He's thinking about doing some work on the [wiki](https://github.com/craftworkgames/MonoGame.Extended/wiki).

But before we go ahead with it I'd like to discuss what we want our documentation to be in #104. I think the first step is to look at documentation in other projects and find some examples of what kind of thing we want.
