### ISSUE TITLE
Would like to add a Drag & Drop library :)

### ISSUE THREAD

**Issue by SoundGoddess** [craftworkgames/MonoGame.Extended#203]
I wrote up this drag and drop library for my own little project, and am happy to contribute it to Extended, along with the demo I made.  Just not sure what all I need to refactor to issue a successful pull request that isn't too big of a pain for you to merge.

I figure I'd rename it to **MonoGame.Extended.DragAndDrop**.

[![Dragon Drop](http://img.youtube.com/vi/AdsWJN4xABI/0.jpg)](http://www.youtube.com/watch?v=AdsWJN4xABI)

https://github.com/MetaSmug/RollYourOwnGameEngine/tree/master/MonoGame.Ruge/DragonDrop
https://github.com/MetaSmug/RollYourOwnGameEngine/tree/master/Demos/Demo.DragonDrop

I'm happy to integrate anything I figure out with Ruge project into Extended.  I just ask for reasonable attribution.

**Comment by craftworkgames** [comment]
Hey

So there's a couple of things I should probably mention first:
 - We already have *some* [drag and drop functionality](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/InputListeners/MouseListener.cs#L43) in the library as part of the mouse listener.
 - I actually wrote a basic [drag and drop handler](https://github.com/craftworkgames/MonoGame.Extended/blob/game-solitare/Source/Demos/Demo.Solitare/DragHandler.cs) just the other day as part of the solitaire demo branch.

That said, there's always room for improvements. The drag handler I wrote for the solitaire demo hasn't get been included in the library, so we could center this discussion around if / what we actually want to include in the library.

I think there's some value in having a drag and drop class somewhere in the library but I'm not exactly sure where it should live or how people would be expected to use it. The one in the demo is generic in a sense, but it's not intuitive to use.

Should it be part of the input listeners somehow? A separate class? Or a game component? Are there other related classes that could be grouped together in the same namespace? etc.

**Comment by craftworkgames** [comment]
> I'm happy to integrate anything I figure out with Ruge project into Extended. I just ask for reasonable attribution.

Oh, yeah and I probably should mention I appreciate the offer. I'm sure we can find ways to help each other. I'll keep an eye on Ruge to see how it evolves. It's a pretty neat idea.

I did notice some unusual code in the implementation. For example:

    public IEnumerable<T> Items {
            get {
                _items = _items.OrderBy(z => z.ZIndex).ToList();
                foreach (var item in _items) { yield return item; }
            }
        }

Could be simplified to: 

    public IEnumerable<T> Items => _items.OrderBy(z => z.ZIndex);

This is using C# 6 syntax to keep it short but that's not really the point. The real issue with the code is that you're iterating over the collection too many times. Once by calling `ToList` and again with the  `foreach` statement. Both of these are unnecessary and will have a performance impact.

I assume you've unintentionally got into a habit of writing `IEnumerable` getters this way. It's an easy enough mistake to make, I just wanted to point it out so that you can address it sooner rather than later.

**Comment by SoundGoddess** [comment]
Yeah I realize that my DragonDrop class isn't that intuitive or elegant.  Might not be the right way to do things, but without finding any other examples out there, that is what I came up with.  Yours may not be that intuitive, but it certainly seems simpler than my version.  I'm hesitant to use the Extended InputListener class though because IIRC it seemed to cause serious issues when Synergy is running on my Mac.  I'm only using Mac for deployment purposes so I don't feel like dealing with a second keyboard and mouse to test my games on there.

**Comment by SoundGoddess** [comment]
Alright, now that I spent all day yesterday debugging and playing with resharper, I realized that the code that I forked just really sucks so I'm re-writing this from scratch to make it clean and understandable.

**Comment by craftworkgames** [comment]
Yeah, Resharper is definitely a good learning tool. Even after 20 years experience as a programmer I installed Resharper and learned quite a few new things.

The importance of clean code is often underestimated. Not only is it easier to understand, but it usually has less bugs because it's more obvious what it's actually doing.

**Comment by SoundGoddess** [comment]
Yeah I like it for the most part, although sometimes the auto-complete is a little screwy and I really question the logic behind changing over nested if statements to an old basic-style continues (not going to do that, it seems way confusing to me).

Anyway, I spent today re-writing the DragonDrop class from scratch.  Now just working on refactoring my demo app.

**Original:** 

https://github.com/MetaSmug/RollYourOwnGameEngine/blob/master/MonoGame.Ruge/DragonDrop/DragonDrop.cs

**New:**

https://github.com/MetaSmug/RollYourOwnGameEngine/blob/dev-dragondrop/MonoGame.Ruge/DragonDrop/DragonDrop.cs

**Comment by craftworkgames** [comment]
> I really question the logic behind changing over nested if statements to an old basic-style continues

Yeah, there's always going to be refactors you disagree with. The best way to deal with those is to change the inspection severity to your liking.

![image](https://cloud.githubusercontent.com/assets/3201643/15632667/3d241954-25dd-11e6-9e07-c726695f339f.png)
