### ISSUE TITLE
Suggestion: Camera2D to follow object

### ISSUE THREAD

**Issue by SlowLogicBoy** [craftworkgames/MonoGame.Extended#207]
I'm thinking about removing some of my logic from my game and referencing this project instead. 
And I can see that here I need to worry about moving the camera myself (outside camera object) to certaing position. 
How about adding IFocusable (or something like that) to camera so camera could follow target by itself?
```
public interface IFocusable
{
    Vector2 Position
}
public class Camera2D : IMovable, IRotatable
{
    ....
    public float MoveSpeed { get; set; }
    public IFocusable Focus { get; set; }
    public void Update(GameTime gameTime)
    {
        if (Focus != null)
       {
            var delta = (float)gameTime.ElapsedGameTime.TotalSeconds;
            Position.X += (Focus.Position.X - Position.X) * MoveSpeed * delta;
            Position.Y += (Focus.Position.Y - Position.Y) * MoveSpeed * delta;
        }
    }
}
```
To avoid hardcoded fuction how to move camera we could use something like:
``` Func<IFocusable, GameTime, Vector2> MovementFunction;```

**Comment by craftworkgames** [comment]
It's an interesting idea but I think there's plenty of ways to do this without modifying the camera class.

The `IMovable` interface is the same as the `IFocusable` one you've defined so that's not needed.

The way I would do it is to create a class that takes 2 `IMovable`'s and causes the first one to be followed by the second one. For example:

   _cameraTracker = new FollowTracker(_camera, _target);

The update method could be essentially the same.

The benefit of this approach, aside from decoupling it from the camera is that you could have any `IMovable` follow any other `IMovable`.

**Comment by SlowLogicBoy** [comment]
Ok, haven't thought about this way. Thanks.
