### ISSUE TITLE
Tiled map becomes black when the size is too big

### ISSUE THREAD

**Issue by rafaelalmeidatk** [craftworkgames/MonoGame.Extended#220]
I am facing a very annoying bug. When the map size is bigger or equals to 129 tiles, it becomes all black, including the transparent areas (where doesn't have anything). The tile size is 32px. I also tested it with the latest version of the develop branch, and it still occurs, but the width need is less, because the tile size is bigger. So, to the bug occurs with:

**32px:** Width >= 129
**128px:** Width >= 33

The most strange is that this don't occurs with my friend, only with me. Here is a screenshot:
![Screenshot](http://i.imgur.com/CjFCert.png)
The map data is correct (the blocked tiles are shown), but the entire map becomes black. There are sprites behind the map (the background that isn't part of the map), but they aren't drawn.

**Comment by craftworkgames** [comment]
Wow. That is super annoying.

My guess is that it's probably running out of texture memory on the graphics card. Which would explain why it's different on your friends computer (because he probably has more memory available). Of course, that's just a guess, I could be completely wrong.

There are a number of issues now that will hopefully be solved if we re-write the renderer to use a mesh rather than a big render target. Unfortunately, this will require a significant about of work so there's no easy fix.

**Comment by rafaelalmeidatk** [comment]
> My guess is that it's probably running out of texture memory on the graphics card. Which would explain why it's different on your friends computer (because he probably has more memory available).

Yes, maybe it is. He tested with 600 tiles and the map turned all black too. I will search about that and try to do something (I am very inexperienced about this things of drawing at the moment), with this tile limits we can't continue testing the maps in-game.

**Comment by rafaelalmeidatk** [comment]
The main problem is this line on _TiledMap.cs_:

    _renderTarget = new RenderTarget2D(graphicsDevice, width*tileWidth, height*tileHeight);

This creates a very, very large render target. I have tested this project and it was able to load a 5000x50 map without lag or black screens. Analysing the code, it draws the map directly on the sprite batch, why do we need a render target? I tried to take out the render target, but then I was unable to render the map correctly with the viewport and camera. Still trying.

**Comment by LithiumToast** [comment]
I think this probably going to be fixed by #221.

**Comment by rafaelalmeidatk** [comment]
Yeah I know, I am just trying to rewrite the renderer in some way to continue testing my game by now.

**Comment by craftworkgames** [comment]
> why do we need a render target?

The reason we used a render target was to solve on old bug when the camera was zoomed in or out. 

You see, when you draw the tiles with a `SpriteBatch` and apply a zoom level with the camera (which is actually a transform matrix on the sprite batch) what it actually does is scale each and every tile individually. This means the tiles do not line up pixel perfectly and you end up with visible gaps between some of the tiles at different zoom levels.

Rendering to a render target is a way to solve this problem because it renders the map to a large "sprite" first and scales the whole thing all at once.

Obviously rendering to a render target has it's downsides. The current issue being that the map requires more texture memory as it gets larger. In the original implementation, this wasn't actually the case. The first thing I tried was to render only the visible part of the map to the render target, but unfortunately while this helps with the memory problem, it really kills frame rate performance.

So yes, I think #221 is the only real way to solve all of the problems at once. I'm sure it's possible to hack together a temporary solution by removing the render target, but imho your time would be better spent working on #221 if you can.

**Comment by rafaelalmeidatk** [comment]
Got it, thanks.

> So yes, I think #221 is the only real way to solve all of the problems at once. I'm sure it's possible to hack together a temporary solution by removing the render target, but imho your time would be better spent working on #221 if you can.

It is true, I'm working on this issue, but I have no idea what I'm doing, so maybe it will take some time.

**Comment by rafaelalmeidatk** [comment]
Problem solved, so this issue can be closed.

**Comment by rafaelalmeidatk** [comment]
Problem solved by #221, so this issue can be closed.
