### ISSUE TITLE
Rewrite the Tiled Map renderer so that it solves a bunch of bugs

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#221]
We've been tossing around the idea for a while now to re-write the Tiled Map renderer to render the tiles using a "mesh" based approach rather than using a sprite batch. This is similar to how a terrain is rendered in a 3D engine.

It should solve a bunch of problems including:
- #220 and #136 which seem to be related to the render target using too much memory
- [this one](http://community.monogame.net/t/draw-tiledmap-strange-borders-around-animated-tiles/7852) that causes animated tiles to be rendered with strange artifacts

There's certainly no lack of [Tiled Map Renderers](http://doc.mapeditor.org/reference/support-for-tmx-maps/) to study. I'm sure we could find a good implementation among them, even if it's written in a different language.

Anyone interested in taking this on?

**Comment by LithiumToast** [comment]
I have been dealing with some rendering stuff recently. I'm probably not going to get around to do this, but I think the best approach to solve this is the following:

- Create a static vertex buffer. The vertex type could be `VertexPositionTexture` since I don't think tiles can be tinted?
- Add vertices into an array of type `VertexPositionTexture[]` with triangle strip topology for each row of tiles associated with a tile layer. Rows can be connected with [degenerate triangles](http://gamedev.stackexchange.com/questions/92034/draw-multiple-triangle-strips-in-one-draw-call-directx). Layers themselves could also be connected using degenerate triangles as longs the depth or Z value is appropriately set for each vertex associated with a layer. (I would assume people want to use `SpriteBatch` to render things in-between layers.)
- Copy the array of vertices into the vertex buffer.
- Bind the vertex buffer to the graphics device. `GraphicsDevice.SetVertexBuffer()`
- Render the entire vertex buffer if layers are connected using degenerate triangles or render a subset of the buffer for each layer. `GraphicsDevice.DrawPrimitives()`

**Comment by craftworkgames** [comment]
Thanks @LithiumToast. That's exactly what I had in mind.

**Comment by LithiumToast** [comment]
@craftworkgames I just realized something... The texture values per vertex can't always be shared between two tiles making triangle strip primitive type not very practical. For example, two tiles side by side share two vertices with the same position attributes, but may have different texture coordinate attributes. 

I guess triangle list vertices with an `IndexBuffer` is the way to go but then this will not fix the old problem of tearing / gaps. It will however fix memory issues with large maps and reduce CPU work since vertices for the map are not computed every frame.

To solve the gaps issue, neighbouring tiles need to have the same vertex position attributes. This pretty easy to control if the vertices are created manually.
To solve the tearing issue the sampling mode for textures needs to be set to clamped.

**Comment by LithiumToast** [comment]
@ whoever tackles this issue:

Each tile is composed of 4 vertices like in the following diagram.

<img width="251" src="https://cloud.githubusercontent.com/assets/519592/16663548/45dad57a-4431-11e6-8359-90d3f4a3ed9d.png">

Each vertex needs at least a position and a texture coordinate attribute and possibly a colour attribute. Either the `VertexPositionTexture` struct or the `VertexPositionTextureColor` struct from MonoGame will work.

In XNA / MonoGame, graphic primitives are either triangles or lines, and each can be connected using lists or strips. In this case we want to use a triangle list, or `PrimitiveType.TriangleList`, because each vertex of a tile is going to be fairly unique with different positions and texture coordinates. `SpriteBatch` also uses `PrimitiveType.TriangleList`.

Thus, to render the tile using graphic primitives, the tile will need to be broken into two triangles like in the following diagram.

<img width="252" src="https://cloud.githubusercontent.com/assets/519592/16664057/615489f2-4433-11e6-99bd-c531bdae11c0.png">

The first triangle is outlined in blue, the second in red. The arrows show how each vertex of the two triangles are connected. The first triangle uses vertices: A, B, C. The second triangle uses vertices: B, D, C.

The order of the vertices which make each triangle plays an important role. The GPU can be instructed not to render triangles in either counter-clockwise or clockwise triangle winding. The idea is that in 3D games which use clockwise triangle winding order for their models, only clockwise winding triangles will be facing the camera. Thus, any counter-clockwise winding triangles can be discarded early. This technique is called back-face culling and can increase performance in 3D games. In XNA / MonoGame the default culling mode is to cull counter-clockwise winding triangles. Because we don't know how people are going to use this code it's best to stick to default settings, or clockwise winding triangles, so everything just works without having to change anything.

Each vertex is going to need texture information. Unlike, the `SpriteBatch` API, the 4 vertices which make up a tile does not know what texture is being used. Instead, the vertices only know the position within texture they should use. These are called texture coordinates and they are normalized, meaning they are in a range from 0 to 1, where (0, 0) is the top-left of the texture and (1,1) is the bottom-right of the texture. Thus to go from a source rectangle like in the `SpriteBatch` API to texture coordinates is fairly straightforward; here's a snippet of code demonstrating this.

```
Texture2D texture = ...;
Rectangle? sourceRectangle = ...;
var textureCoordinateTopLeft = Vector2.Zero;
var textureCoordinateBottomRight = Vector2.One;

            if (sourceRectangle.HasValue)
            {
                var rectangle = sourceRectangle.Value;
                textureCoordinateTopLeft.X = rectangle.X / texture.Width;
                textureCoordinateTopLeft.Y = rectangle.Y / texture.Height;
                textureCoordinateBottomRight.X = (rectangle.X + rectangle.Width) / texture.Width;
                textureCoordinateBottomRight.Y = (rectangle.Y + rectangle.Height) / texture.Height;
            }
```
Then once the top-left and bottom-right coordinates are found the vertices will use the following information.

```
topLeftVertex.TextureCoordinate = textureCoordinateTopLeft;
topRightVertex.TextureCoordinate = new Vector2(textureCoordinateBottomRight.X, textureCoordinateTopLeft.Y);
bottomLeftVertex.TextureCoordinate = new Vector2(textureCoordinateTopLeft.X, textureCoordinateBottomRight.Y);
bottomRightVertex.TextureCoordinate = textureCoordinateBottomRight;
```
To render the tiles, the vertices will first need to be "uploaded" to the GPU. This is accomplished using a `VertexBuffer`. In our case, we also want to use an `IndexBuffer`, since the two triangles which form a tile share vertices. In the last diagram, the first and second triangle use the same vertices: B and C. It would be waste of resources to have the same vertex information duplicated and sent to the GPU. Instead, only the 4 unique vertices need to be sent to the GPU along with 6 indices referencing the vertices of the two triangles (3 indices per triangle). The vertex A will get the index 0, B will get 1, C will get 2, and D will get 3. The indices for the two triangles which form the tile will always be the same: 0, 1, 2, 1, 3, 2.

Snippet for creating the vertex and index buffer: 
```
GraphicsDevice graphicsDevice = ...;
int maximumVerticesCount = ...;
int maximumIndicesCount = ...;
var vertexBuffer = new VertexBuffer(graphicsDevice, typeof(VertexPositionTexture), maximumVerticesCount, BufferUsage.WriteOnly);
var indexBuffer = new IndexBuffer(graphicsDevice, typeof(uint), maximumIndicesCount, BufferUsage.WriteOnly);
```

Snippet for creating and filling arrays:
```
// create
int maximumVerticesCount = ...;
int maximumIndicesCount = ...;
int vertexCount = 0;
int indexCount = 0;
var vertices = new VertexPositionTexture[maximumVerticesCount];
var indices = new uint[maximumIndicesCount]

...

// fill in a tile

var indexOffset = vertexCount;

VertexPositionTexture topLeftVertex = ...;
VertexPositionTexture topRightVertex = ...;
VertexPositionTexture bottomLeftVertex = ...;
VertexPositionTexture bottomRightVertex = ...;

vertices[vertexCount++] = topLeftVertex;
vertices[vertexCount++] = topRightVertex;
vertices[vertexCount++] = bottomLeftVertex;
vertices[vertexCount++] = bottomRightVertex;

indices[indexCount++] = 0 + indexOffset;
indices[indexCount++] = 1 + indexOffset;
indices[indexCount++] = 2 + indexOffset;
indices[indexCount++] = 1 + indexOffset;
indices[indexCount++] = 3 + indexOffset;
indices[indexCount++] = 2 + indexOffset;

```

Snippet for binding buffers:
```
GraphicsDevice graphicsDevice = ...;
graphicsDevice.SetVertexBuffer(vertexBuffer);
graphicsDevice.Indices = indexBuffer;
```

Snippet for rendering:
```
GraphicsDevice graphicsDevice = ...;
Effect effect = ...;
int indexCount = ...;
int primitiveCount = PrimitiveType.TriangleList.GetPrimitiveCount(indexCount);
foreach (var pass in effect.CurrentTechnique.Passes)
{
    pass.Apply();
    graphicsDevice.DrawIndexedPrimitives(PrimitiveType.TriangleList, 0, 0, primitiveCount);
}
```

**Comment by rafaelalmeidatk** [comment]
@LithiumToast thank you! I did something [here](https://github.com/craftworkgames/MonoGame.Extended/pull/223), can you see it? There are gaps between the tiles, IDK how to solve it. I was thinking in using triangle strip, but there are the problems that you mentioned.

![screenshot_35](https://cloud.githubusercontent.com/assets/11896398/16676351/d05f6f6c-449f-11e6-99f1-8d34723e97c9.png)

The positions of the vertices are exactly the same, as you can see here:

![screenshot_36](https://cloud.githubusercontent.com/assets/11896398/16676442/8778d36e-44a0-11e6-90ba-dd8d53956e36.png)

What could I try?

**Comment by LithiumToast** [comment]
@rafaelalmeidatk You could try setting the sampler state to `PointClamp`:

```
GraphicsDevice.SamplerStates[0] = SamplerState.PointClamp;
```

**Comment by rafaelalmeidatk** [comment]
@LithiumToast it didn't work, the gaps remains.

**Comment by LithiumToast** [comment]
@rafaelalmeidatk Hmm. For sanity sake, trying setting all 16 sampler states to point clamp.

This problem of gaps between tiles was the original problem which render targets were used to solve for. But we can't use render targets because it uses too much memory. Triangle strips won't help here because each vertex has different texture coordinates.

**Comment by LithiumToast** [comment]
@rafaelalmeidatk I cloned your work and tested `SamplerState.PointClamp` it fixes the issue.

**Comment by craftworkgames** [comment]
The bugs in this issue seem to be covered. 

Probably best to raise a new issue for each new individual bug in future.
