### ISSUE TITLE
[Collision] Collision Handling Priorities

### ISSUE THREAD

**Issue by Acolit** [craftworkgames/MonoGame.Extended#228]
Although work is being done to find a potential replacement to the current collision detection system, I decided to open that issue in case someone wants to keep the current one in their game, or as a bit of insight that could aid in the making of the replacement.

The way `CollisionGrid` and `CollisionWorld` work right now is like this: For each actor attached to the `CollisionWorld` object, `CollisionGrid` will first check every cell its bounding box is intersecting with, then it keeps and returns only the cells flagged as being "solid" (when using an imported Tiled map, this is basically any tile on the selected collision layer that isn't empty). `CollisionWorld` then checks each returned cell in reading order (left to right, top to bottom) to see if they are still intersecting with the actor's bounding box, calls the actor's `OnCollision()` method with the `CollisionInfo` of that cell if it does, and moves directly to the next cell in line if it doesn't.

![Example of collision handling steps.](http://i.imgur.com/2JOGkz9.png)

> Here's a more visual example. The collision handling code is the same found in the Zombie class in the SpriteSheetAnimator demo.

While this system is simple enough for most cases, it can become a bit of a problem when the `CollisionWorld` object uses gravity. The cells being checked in reading order for a standard downwards gravitational force used in most 2D platformers is pretty nice, but this brings a problem when the actor is intersecting a wall tile in such a way that `CollisionWorld` interprets it as a ceiling tile collision and acts as such before discovering that there is a colliding tile right below it.

![When this issue is most likely to happen.](http://i.imgur.com/lYBsX0A.png)

> The Y velocity doesn't really matter: As long as the actor is intersecting in this manner, the result will be the same, and from experience, setting more conditionals breaks stuff as much as it fixes it. Furthermore, pushing against a wall while falling causes the same issue to happen at each cell or so.

I wrote a workaround [here](http://pastebin.com/qFk8h6NM) that applies to my case and doesn't involve modifying the source code, but if I had a different directional gravity, I would most likely run into other problems. I have thought of multiple ways of figuring it out, and one of those would be to have a way to skip some tiles if the grid cell opposite to `c.PenetrationVector`'s direction contains a solid tile, which isn't really possible right away because of how `OnCollision()` currently doesn't get much insight about neighboring tiles. Another was to test conditionals to narrow down the possibility that this is a ceiling collision, but there doesn't seem to be an actual way to do so simply.

In any case, this may be something that is good to know for whoever modifies that bit of code.

**Comment by craftworkgames** [comment]
@Acolit Thanks for the detailed bug report :smile: 

As you know `CollisionWorld` is a very basic implementation that really only works for demo purposes. To be honest, I'm not sure where we are at with the re-write. I think @LithiumToast has it on his to-do list to get back to eventually but I'm not sure about the timeline.

At this stage I'm thinking we should pull the existing `CollisionWorld` code out of the library but keep it in the demo so that we have a copy of it for anyone still using it.

On another note, I created a [new repo](https://github.com/craftworkgames/MonoGame.Extended.StarterKits) the other day for "starter kits" and the first one I'd like to create is a 2D platformer. I haven't written a lot of code yet, but what I have done is a very basic prototype using placeholder assets and basic collision detection. Hopefully this will help evolve the library in the right direction and make it easier to make decisions around the collision stuff in the library.

**Comment by LithiumToast** [comment]
You can see my work on [`CollisionSimulation`](https://github.com/LithiumToast/MonoGame.Extended/blob/collision-detection/Source/MonoGame.Extended/Collisions/CollisionSimulation.cs) in my fork. It's coming along slowly.
