### ISSUE TITLE
[Demo] Platformer & vNext

### ISSUE THREAD

**Issue by LithiumToast** [craftworkgames/MonoGame.Extended#238]
Goals:
- Create platformer game demo. Use the game demo to drive the development for the following:
  - Entity component system.
  - Tiled renderer / object parser.
  - Collisions.

I would also like to take the time to document things with XML as things go from being fleshed out to approaching polishing. It's easier to document things when it's still fresh in our cognitive cache if you will. Documentation is also pretty lacking in general, so it be nice to have a policy to force it to happen at least with XML documentation for new code.

EDIT: For documentation I use the free version of [GhostDoc](http://submain.com/products/ghostdoc.aspx) for VisualStudio to automatically generate the boilerplate XML for each class, struct, enum, etc by using the shortcut `CTRL+SHIFT+D` when the mouse cursor is over the name of a class, struct, enum, etc. Then documentation is easy as just filling the XML in. I also use ReSharper to format the XML to the expected standard once I'm done filling in the XML.

**Comment by craftworkgames** [comment]
Thanks @LithiumToast. I couldn't have said it better myself. Here's what we've got so far:

![image](https://cloud.githubusercontent.com/assets/3201643/17890794/78a2a5e0-697b-11e6-9a53-ca946ac294d2.png)

There's still plenty to do but I think creating a real game demo is a great way to drive the development of the library. A collaborative open source game to drive the development of a library is a bit of an experiment but if it works out I'd like to continue to do it.

Let's treat this as the next milestone release.

**Comment by craftworkgames** [comment]
I found a couple of good reads when implementing platformers

[The guide to implementing 2D platformers](http://higherorderfun.com/blog/2012/05/20/the-guide-to-implementing-2d-platformers/)

[Super Nerd Boy - on jumping game feel](http://meyermike.com/wp/?p=160)

**Comment by DigitalLibrarian** [comment]
Have any strong feelings for the feature set in this game?

**Comment by craftworkgames** [comment]
> Have any strong feelings for the feature set in this game?

I have a few ideas but I wouldn't call them strong feelings. I'd prefer the game was a collaborative effort, so if you have ideas for the feature set, by all means, lay them out here please.

Currently, my thought is that we want to keep the game fairly simple in order to actually finish it.
 - The goal is to get the player out of the right side of the screen without dying. 
 - We'll have some level based hazards along the way, like those deadly spikes. 
 - A couple of different type of enemies.
 - Maybe a 3 heart health system.
 - Some collectibles. Hearts for health, coins perhaps, other power-ups?

Usually I like to have some puzzle elements in the levels, but I'm also particualarly interested in exploring [game feel](https://www.youtube.com/watch?v=AJdEqssNZ-U) and adding some juice to the game, which might lend itself more to an action style game perhaps.

What are your thoughts?

**Comment by craftworkgames** [comment]
![player-death](https://cloud.githubusercontent.com/assets/3201643/18027794/9ffd1c64-6cb0-11e6-97ba-90b6c0382e9e.gif)

I was implementing player death tonight and I ran into an interesting problem. When the player dies, it spawns a new entity for the "blood splatter explosion". This looks quite effective, the problem is that this new entity needs to be destroyed after the explosion animation completes. Currently it's just hanging around in memory forever.

**Comment by LithiumToast** [comment]
@craftworkgames This is what object pooling is for.

**Comment by craftworkgames** [comment]
Object pooling will be useful at some point for memory optimizatin, but that's really not what I'm talking about.

The question is how to *trigger* the deletion of an entity. In this particular case, we want to delete the entity once the particle emitter has finished emitting particles.

We could take a more general approach and attach some kind of `LifeSpan` or `TimeOut` component that deletes the entity after some specified time as passed. That would certainly solve the problem but it might not be clear that it needs to be attached to the entity in the first place.

I doubt I'm the first person to run into this issue with in an ECS though, I'll bet Unity and Artemis have some standard pattern for this kind of stuff.

**Comment by craftworkgames** [comment]
Well that makes sense, [Unity `Destroy`](https://docs.unity3d.com/ScriptReference/Object.Destroy.html) has a second parameter that delays the destruction. It works for entities and components alike.

**Comment by craftworkgames** [comment]
There's a really good talk by Vlambeer and I've always really wanted to implement some of this cool stuff. So yeah, let's do it.

[Jan Willem Nijman - Vlambeer - "The art of screenshake"](https://www.youtube.com/watch?v=AJdEqssNZ-U)

 - basic animation and sound effects
 - lower enemy hp
 - higher rate of fire
 - more enemies
 - bigger bullets
 - muzzle flash
 - faster bullets
 - less accuracy
 - impact effects
 - hit animations
 - enemy knockback
 - permanence
 - camera lerp
 - camera position relative to the player
 - screen shake
 - player knockback
 - sleep (pause in moments of impact)
 - gun delay
 - strafe
 - gun shells
 - more bass in the sound effects
 - super machine guns
 - random explosions
 - faster enemies
 - more enemies
 - even higher rate of fire
 - camera kick
 - bigger explosions
 - smoke
 - meaning

**Comment by craftworkgames** [comment]
The platformer demo has some value already but there doesn't seem to be any more interest in working on it to completion. No need for this issue to stay open.
