### ISSUE TITLE
AnimatedSprite automatically playing an animation

### ISSUE THREAD

**Issue by TheUltimateHose** [craftworkgames/MonoGame.Extended#243]
In recent Previews (I tested/used 0.5.418, 0.5.441), `SpriteSheetAnimator` is being replaced by `AnimatedSprite`. One major difference is that `AnimatedSprite` takes a string as constructor parameter which is used to immediately play a looping animation which _can_ be useful sometimes, but in cases like mine (player animation) it would probably considered a bug if the animation plays right from the start without the player actually doing anything.

My idea:
- Leave [that line](https://github.com/craftworkgames/MonoGame.Extended/blob/2d4653340a5dfa04e7cef1df49a1335f089e80f4/Source/MonoGame.Extended/Animations/SpriteSheets/AnimatedSprite.cs#L14) out
- Make a second constructor that doesn't play an animation right away

**Comment by craftworkgames** [comment]
Hey @TheUltimateHose. Sorry I didn't get back to you about this sooner.

Here's the thing... the `AnimatedSprite` class is brand new. I wrote it as an experiment to see how it might work with the Entity Component System because the `SpriteSheetAnimator` wasn't a very good fit. The current implementation is far from complete. I really just did the bare minimum to test out the idea.

The good news is that I'll shortly be using it for player animation in the Platformer demo. I'll be making many improvements to it shortly (including those you mentioned above) and have a demo to show how it works. 

Now that we are on the topic though, I'd be interested to hear more about your particular use cases.

> it would probably considered a bug if the animation plays right from the start without the player actually doing anything.

I can understand the desire to have a constructor that doesn't play any animation. I was planning on adding that anyway. Although, I would have thought in most cases for player animation you'd want some kind of "idle" animation to play by default.

**Comment by TheUltimateHose** [comment]
> Although, I would have thought in most cases for player animation you'd want some kind of "idle" animation to play by default.

Well that's something I didn't thought about, mostly because I don't have an idle animation.

My particular use case is the player in a rpg (like "Zelda" or "Stardew Valley"). I'm currently only using animations for movement, as I don't have an idle animation.
