### ISSUE TITLE
[Shapes] Why is there no Location for PolygonF shape?

### ISSUE THREAD

**Issue by musbah** [craftworkgames/MonoGame.Extended#270]
I was just wondering why both RectangleF and CircleF have a Location of sorts while PolygonF does not.
Is it a decision that was taken? Or was it just forgotten?

I was just wondering because even the drawing functions of RectangleF and CircleF in SpriteBatchExtensions  don't ask for a position while the DrawPolygon does.

Anyway thank you, and I apologize if this is a silly question, I just can't think of a reason as to why it shouldn't be there.

**Comment by craftworkgames** [comment]
Hey, sorry I didn't get back to you about this. There are a no silly questions.

To be honest, I didn't write the `PolygonF` shape so I don't actually know why it doesn't have a `Location`. Maybe there's a reason, but I'm not sure what it is.

What I do know is that @LithiumToast has been working on Shapes in his collision detection fork. Maybe he has some thoughts on it.

**Comment by musbah** [comment]
@craftworkgames I just ended up adding a Location for my own purposes and then I made a Pull Request since I had already wrote it anyway. It would probably be a good idea to wait and see what @LithiumToast thinks before doing anything with that request though.

**Comment by LithiumToast** [comment]
> To be honest, I didn't write the PolygonF shape so I don't actually know why it doesn't have a Location. 

@craftworkgames The Git history says otherwise?

@musbah 
What you probably mean with a "location" for a polygon is a "world" position for the polygon. However, the position of the polygon's points (vertices) are described in "model space" without the world position applied (or any rotations) and thus are "local" positions. It would probably be better to use a `Transform2D` class to hold the local and world positions (as-well as rotations) and then apply it the array of local vertices to get the world vertices which are suitable for rendering or collisions.

Also I don't think `PolygonF` should be a struct since arrays are classes and having members of a struct which are classes is not great for primitives. Primitives should be lightweight and have little consequences for creating them nilly willy.

**Comment by musbah** [comment]
@LithiumToast That makes a lot of sense, Thank you. I was mostly confused because `RectangleF` and `CircleF` both had a `Location`. I'm going to rethink what I did, since there's a better way of doing it. Thanks again, your explanation helped me understand something I had overlooked.

**Comment by craftworkgames** [comment]
> The Git history says otherwise?

Heh, I guess my memory fails me 😄 

Thanks for the explanation @LithiumToast
