### ISSUE TITLE
BitmapFont renders black boxes instead of characters

### ISSUE THREAD

**Issue by streamholder** [craftworkgames/MonoGame.Extended#280]
For some reason, MonoGame.Extended renders by BitmapFont as black boxes.
The descriptor file seems to get loaded, as the character width looks correct. However, everything is rendered as black boxed.
I'm attaching a stripped-down version of my project to test the issue.
[AndroidGame1.zip](https://github.com/craftworkgames/MonoGame.Extended/files/555470/AndroidGame1.zip)

**Comment by musbah** [comment]
I tried downloading your test but it looks like I need Xamarin to make it work and I don't have it (I also have a very slow internet connection so downloading it would take too long), for next time you should probably make it a regular project.

Anyway I copied everything over to another project and your problem is the background color of your assets. If you change the color of the `DrawString` to red `spriteBatch.DrawString(font,"Balocco di prova", new Vector2(50,50),Color.Red)`, you'll see that you can actually see the text, it's just that the background color of your asset is black.

**Comment by streamholder** [comment]
I'm using Xamarin to target Android, I cannot use a regular project.
About the assets, I think I see the problem: my PNG file doesn't have an alpha channel, and the library cannot handle that correctly. I'll test the issue further, and I'll consider submitting a patch if I can fix it in a reasonable time :)

On 27 Oct 2016, at 1:56 PM, musbah <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried downloading your test but it looks like I need Xamarin to make it work and I don't have it (I also have a very slow internet connection so downloading it would take too long), for next time you should probably make it a regular project.

Anyway I copied everything over to another project and your problem is the background color of your assets. If you change the color of the DrawString to red spriteBatch.DrawString(font,"Balocco di prova", new Vector2(50,50),Color.Red), you'll see that you can actually see the text, it's just that the background color of your asset is black.

**Comment by musbah** [comment]
@streamholder I know you are using Xamarin, I just meant if it's for testing purposes (as in to show other people) you might as well have just used a desktop template.

**Comment by craftworkgames** [comment]
> About the assets, I think I see the problem: my PNG file doesn't have an alpha channel, and the library cannot handle that correctly. I'll test the issue further, and I'll consider submitting a patch if I can fix it in a reasonable time :)

We don't support PNG's without an alpha channel. You're welcome to try and submit a fix if you want but to be honest I don't think it's a big issue (unless I'm missing something). 

I'm gonna close this issue but you can still submit a fix if you want.
