### ISSUE TITLE
[Tiled] Tile animations are broken

### ISSUE THREAD

**Issue by HyperionMT** [craftworkgames/MonoGame.Extended#296]
With the new rendering code we're calculating the vertex buffer once when the map is loaded and not updating it.  For the animation to play the texture coordinates need to be updated in the GroupRenderDetails when the frame changes.

In addition it also looks like TiledTilesetTile.Update is not being called, this can probably all be handled by having IMapRenderer implement IUpdate.

**Comment by LithiumToast** [comment]
> texture coordinates need to be updated

The current code makes use of `VertexBuffer` and `IndexBuffer` which are static, rather than dynamic. This is for performance reasons. If dynamic buffers are needed for geometry which changes on a frame-by-frame basis to get tile animations working then perhaps the tile geometry should be split into static and dynamic buffers for rendering.

**Comment by craftworkgames** [comment]
We need to support Tile animations (there's definitely people using this feature).

I'm pretty sure we could code it to get the best of both worlds. It might make the code a little more complex but I think it's worth it to support this feature.

Ideally, people that aren't using animated Tiles shouldn't have to pay the performance penalty. It should possible to split the geometry into static and dynamic buffers, but the impact might be different depending on the map type and rendering order.

**Comment by Spessi** [comment]
Hi,
I don't have that much time during the week, but I've quickly implemented the animations. I'm pretty sure the code isn't really good, but it works: https://github.com/Spessi/MonoGame.Extended/commit/c50de5f302268da78483ba1e64fd3d41e93a5b41

Basically I splitted the static and animated parts into StaticGroupRenderDetails and DynamicGroupRenderDetails. I'm not sure if the method "RebuildDynamicRenderDetails" is efficient, because it has to copy the vertices of each tile, refresh the texture coordinates, and copy the vertices back to the DynamicGroundRenderDetails (which produces a lot of garbage). Besides of that, the code needs to be tidied up and also needs some name refactoring :).

**Comment by craftworkgames** [comment]
@Spessi There's nothing wrong with quickly implementing things. Any progress is good progress.

What I'd like to do at this point is for you to submit the changes as a PR if you could please and perhaps @HyperionMT and @LithiumToast can do a code review before I pull it into the `develop` branch.

The main things we'd be looking for:
 - Do the changes make non-animated rendering worse?
 - Does the public API make sense?

After that, we can look at optimizing the code and reducing the garbage.

There's certainly people that would appreciate having Tile animations working again even if they are not perfect. Your efforts are much appreciated mate :)

**Comment by HyperionMT** [comment]
I agree with @craftworkgames, unless the performance is so bad that it makes it impossible to render large maps (you can test this with the last map in the TiledMaps demo) then submit it and lets worry about optimizing later.  Based on the fact that you're only animating tiles on screen I can't imagine this being the case so I think you're probably good to go.

I took a quick look through your changes (I'll look closer once there's a PR) and the only thing I have to say right now is that I noticed you have the renderer in charge of updating the tiles.  I'm on the fence about whether this is a good idea or not.  On one hand I feel like the map should take care of updating itself (TiledMap.Update which calls TiledTilesetTile.Update) but I can also see that drawing animations is part of rendering the map so it _could_ make sense.  What do you guys think @craftworkgames and @LithiumToast ?

**Comment by craftworkgames** [comment]
I kinda feel like the `TiledMap` class should be about the *data* and not the drawing or updating. 

The reason I say this is because it kinda fits the same model as a `Texture2D` or `BitmapFont`. You're loading the data from the `Content.Load<TiledMap>` call and hanging on to a reference of it. Then you're passing that to the renderer in a similar way to how you pass a `Texture2D` to a `SpriteBatch`. 

Of course, the two examples I used above are about drawing resources. A `TiledMap` is a little bit different in the sense that it both draws and updates. Two other examples come to mind that have this behavior; `SpriteSheetAnimation` and `ParticleEffect`. 

A `SpriteSheetAnimation` on the other hand can be loaded from a JSON file. The way this works is that you actually load a `SpriteSheetAnimationFactory` and spawn instances of `SpriteSheetAnimation`'s from it. This is important because each animation must carry it's own state otherwise they'd all render the same frame at the same time (we actually had a bug like this a while back).

Currently a `ParticleEffect` doesn't have the ability to be loaded with a call to `Content.Load`. However, I think we'll get to that at some point and when we do, we'll probably have to deal with the shared state problem again.

To be honest I hadn't even really considered how it might work having the map in charge of updating. It certainly could be the right way to go in this case. I haven't looked closely at the code yet, so I may have missed something.

Just some food for thought.

**Comment by HyperionMT** [comment]
All good points. Maybe the map isn't the best place to put this but I'm not sure the renderer is either. Take for example a split screen multi-player game. Wouldn't you have 2 renderer for the same map? (I've never tried split screen so maybe that isn't how it would be done) In this case the tile updates would be done twice (or more depending on number of players) messing up the animations and potentially skipping some frames.   To me it seems like we need a centralize

**Comment by Spessi** [comment]
Just for your information, I had some time and cleaned my code, here you can find the PR: https://github.com/craftworkgames/MonoGame.Extended/pull/302

... as I read your split screen argumentation, I think it really makes more sense to do the animation update in the TiledMap class. But to be consequent, we would need to update the texture coordinates in the FullMapRenderer and update the animations in the TiledMap. Therefore, we would need two update calls instead of one. I don't know if that's better.

**Comment by craftworkgames** [comment]
Okay, so Tile animations are working now.

There still seems to be a bug when the camera is zoomed in. After a certain point, the tiles stop animating.

**Comment by craftworkgames** [comment]
> There still seems to be a bug when the camera is zoomed in. After a certain point, the tiles stop animating.

If I comment out these two lines, the problem goes away, so it seems to be something to do with the way the `camViewport` is being calculated.

                    //var rectangle = new Rectangle((int)tile.Position.X * _map.TileWidth, (int)tile.Position.Y * _map.TileHeight, _map.TileWidth, _map.TileHeight);

                    //if (camViewport.Contains(rectangle))

**Comment by LithiumToast** [comment]
@craftworkgames Is the bug still there? Tiled animations work in the demo for the provided input map.

**Comment by craftworkgames** [comment]
Yep. Seems to be working now.
