### ISSUE TITLE
Change the Draw Functions of geometry to use 3D?

### ISSUE THREAD

**Issue by edenprojectde** [craftworkgames/MonoGame.Extended#306]
I saw this:
https://github.com/craftworkgames/MonoGame.Extended/blob/framework-split/Source/MonoGame.Extended/Shapes/SpriteBatchExtensions.cs 

And i thought that this could be much faster if used in conjunction with the 3D features of MonoGame;
Making use of a Basic Effect:
```
...
            basicEffect.View = Matrix.Identity;
            basicEffect.World= Matrix.Identity;
            basicEffect.Projection = Matrix.CreateOrthographicOffCenter(0f, screenwidth, screenheight, 0f, 0f, -1000f);
            basicEffect.VertexColorEnabled = true;

            Manager.Game.GraphicsDevice.SetVertexBuffer(vertexBuffer);
            foreach (var pass in basicEffect.CurrentTechnique.Passes)
            {
                pass.Apply();
                Manager.Game.GraphicsDevice.DrawPrimitives(PrimitiveType.LineList, 0, 7);
            }
...
```
I implemented this becuase of performance reasons into my Current Project. If its helpful i can post the cleaned up Version of the full file later on. If it isn't really performant please tell me so because i always thought this was faster :'D

**Comment by LithiumToast** [comment]
I've been basically working towards this outcome. The problem for rendering shapes is that `SpriteBatch` can only be used to render textured rectangles with color (sprites) and has been optimized for such. Meaning, if people want to draw textured rectangles with color that can change every frame there is no better way than what `SpriteBatch` has to offer. However, this makes it suck to try to do something different like draw shapes with it, something it was not designed for. For example it sucks to create a texture which represents a filled shape just to draw it as a rectangle with `SpriteBatch` (filled shapes are not even supported in the `SpriteBatchExtensions` it seems) because then if the shape changes, the texture has to change too. Stroke is isn't too bad since it's just drawing a series of thick lines as rectangles forming a crude polyline. However `SpriteBatchExtensions` can not easily form polylines with joint and cap ends because it is limited to drawing textured rectangles only. While creating a texture that represents the polyline is one solution, but again this sucks.

I created a  [`DynamicBatch2D`](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Graphics/DynamicBatch2D.cs) which is going be used in the near future for drawing shapes. It uses a little bit more CPU in comparison to `SpriteBatch` when sorting the draw calls by texture or depth but is generic in sense that it can batch any type of geometry. I'm working on having `DynamicBatch2D` render shapes using triangle tessellation (`PrimitiveType.TriangleList`) and I have already got circle, ellipse, arc, rectangle and polygon working for filled shapes. Stroked shapes for now will probably use same technique thick lines as rectangles but I want to get into different joint and end cap types for polylines eventually.
