### ISSUE TITLE
[Tiled] TiledMap.Draw not respecting passed in “visibleRectangle”

### ISSUE THREAD

**Issue by Aurioch** [craftworkgames/MonoGame.Extended#310]
I'm opening the issue from Monogame forum, simply so we can track it here.

[Original post (click):](http://community.monogame.net/t/tiledmap-draw-not-respecting-passed-in-visiblerectangle/8406)

> Trying to draw my TiledMap using this:
> 
> `tiledMap.Draw(spriteBatch, Camera.ViewPort);`
> 
> where Camera.Viewport is the Rectangle defining the area of the map that should currently be visible to the player. However, the draw method always just draws the map from the top left tile, it does not draw the part of the map that the Rectangle defines. What am I missing here? Is this not what the argument "visibleRectangle" is for?
> 
> I'm using Monogame.Extended version 0.5.149

**Comment by craftworkgames** [comment]
Thanks @Aurioch.

I've linked the forum post to this issue so that the OP can find it.

The short answer is, a *lot* has changed since version 0.5.149. It's probably best to try [build from source](https://github.com/craftworkgames/MonoGame.Extended/wiki/Building-MonoGame.Extended-from-source) or use a [pre-release NuGet package](https://github.com/craftworkgames/MonoGame.Extended/wiki/How-to-use-the-pre-release-NuGet-packages)

I'm not entirely certain what the problem is, or if it has been fixed but there's been plenty of activity on the Tiled code recently.

Do we even have the `visibleRectangle` parameter anymore?

@EvilRikard What's your use case?

**Comment by EvilRikard** [comment]
Hi,

it seems like the argument "visibleRectangle" is indeed obsolete now, at least in the development branch of Monogame.Extended that I have now downloaded and built.

However, now my issue is that I cannot even load my TiledMap. Just doing this:

TiledMap test = Content.Load<TiledMap>("test_level");

leads to the unexpected (to me at least) error:

System.ArgumentException has been thrown
An item with the same key has already been added.

How is this possible?
Is this not how TiledMaps are loaded anymore?

**Comment by EvilRikard** [comment]
The error I described above must have been due to the fact that I had one version of MonoGame.Extended as a package (0.5.149) and one version (the dev branch, as a reference).
Now I'm having other troubles instead, with Pipeline tool not starting, but that doesn't belong to this thread.
Thanks for your responses.

**Comment by LithiumToast** [comment]
The non `SpriteBatch` renderer for Tiled doesn't support this. The reason is simply that each draw call can draw up to quite a few tiles (16384).

@craftworkgames This can be closed.
