### ISSUE TITLE
tIDE/xtile

### ISSUE THREAD

**Issue by policeshootout** [craftworkgames/MonoGame.Extended#335]
I asked on reddit about tIDE and xtile working with MonoGame and was suggested to submit an issue here to possibly find a library that works with MonoGame. I haven't yet started my project so perhaps using something like Tiled would be easier/better? But if somebody has any experience getting tIDE/xtile to work with MonoGame, any suggestions would be greatly appreciated :)

**Comment by LithiumToast** [comment]
Hey thanks for posting. It appears tIDE has a [XNA 4.0 implementation](https://tide.codeplex.com) which should work with MonoGame. If not we can probably support it here directly as a separate library with MonoGame.Extended by ripping it apart.

**Comment by craftworkgames** [comment]
I used tIDE on a project once, a long time ago. It's quite good and there are ways to get it working with MonoGame. I actually answered a similar question [on stack overflow](http://stackoverflow.com/questions/16640261/xtiled-in-monogame-import-tmx-maps-in-monogame) at the time. If I remember correctly I downloaded the source code to xTile and hacked at it until I got it working.

The thing is though, we've talked about adding tIDE support to MonoGame.Extended before #23 and there just wasn't any interest in it at all. Most people around here seem to prefer Tiled.

So your best option is probably to use Tiled instead, but if you want, you could go the other way and get tIDE working.

**Comment by policeshootout** [comment]
I did see both of those posts before, thanks! I'm very new to C# and almost everything else involved in any sort of game development. I have experience in HTML and VB6 but that's it, and it was a long time ago. I am hoping to just jump in but I think I am trying to bite off more than I can chew at one time. 

I'll keep messing around with it but I might just end up going with Tiled since it's more supported and seems like there's more interest in it.

**Comment by colinvella** [comment]
I guess I'm slightly late for the party but I'm the author of tIDE and xTile. I have to admit that I haven't worked on this project for a while and I have no experience with Monogamy.  However please do let me know if I can be of any help :)

Currently I'm moving the project to GitHub as CodePlex is closing down by the end of the year.

**Comment by colinvella** [comment]
GitHub repo here: https://colinvella.github.io/tIDE/
Web site is still WIP

**Comment by craftworkgames** [comment]
Hey @colinvella. Nice you meet you. I used tIDE and xTile on a project a few years ago and it was quite nice. Thanks for that.

We've put a whole lot of work in our Tiled package and it's one of our most popular features. Most people seem to be happy with it.

Strictly speaking, the way we've decided to structure MonoGame.Extended with different packages for each high level purpose, we could possibly create a `MonoGame.Extended.xTile` package or something like that. The main reason I haven't done this already is the overhead of maintaining another package.

So far all of our packages have quite different purposes with the exception of the two GUI packages (one is a port of another library and the other is hand rolled from scratch). This is okay for now but there's an open question about whether we'll keep both packages in the future, time will tell.

That said, I realize each project has it's pros and cons. I'm sure tIDE + xTile have some interesting features that don't come out of the box with Tiled. I'm sure you've got plenty of new ideas floating around in your head. I'm definitely interested to hear your thoughts and ideas for your project.

I have perhaps a somewhat controversial idea. Maybe you could become the primary maintainer of the `MonoGame.Extended.xTile` package. I'm not sure how this would work exactly, I guess the simplest way is for you to have a fork of my repo and make regular pull requests back into it. You could of course also have a dependency free version if you can figure out the technicalities. 

Anyway, I'm super excited to see you've revived the project. There seems to be a [bit of that](https://github.com/VelcroPhysics/VelcroPhysics) going on lately ;) I'll definitely keep an eye on it.

**Comment by craftworkgames** [comment]
Oh, btw.. I think you should have a link to the Github repo on the website. I had to figure it out by finding your username.

**Comment by colinvella** [comment]
I'm glad you found tIDE and xTile useful! :)

My interest in tIDE had waned a bit when Microsoft stopped supporting XNA but I do realise the technology (XNA) is still in use either in its original form or its Monogame incarnation. I think that, if xTile is to have a future, it ought to be as a Monogame extension. As I have stated in an earlier post, I have next to no experience with Monogame itself, so I have yet to understand what changes were (and may still be) needed in xTile.  Tiled has benefited from regular maintenance and improvements by its dedicated author (kudos to Thorbjørn! 🥇) so there is a lot of work to be done to get tIDE and xTile on par with Tiled and the corresponding rendering engine.

I do see your point in the attraction of having one good tile rendering solution rather than two packages that seem to do similar things. Perhaps the main redeeming feature of xTile is that it's a rendering engine that was designed to be tightly integrated with the XNA content framework. The one other feature that, to my knowledge, seems to lack in other tile map editors is support for parallax maps. With tIDE, it is easy for the level designer to see how the different layers line up when designing maps.

I'm keen to hear your thoughts on how xTile could become a more useful Monogame extension. As it stands, it is in a somewhat dormant state, but perhaps we can take it forward in a direction that would benefit Monogame developers more. I am definitely excited to take on your offer to maintain xTile as a Monogame extension. Please let me know if there is anything that needs to be addressed with the current codebase.

P.S. I'll be adding a link to the GitHub repo soon. I'm still refining the page in my spare time :)

**Comment by craftworkgames** [comment]
> I'm keen to hear your thoughts on how xTile could become a more useful Monogame extension.

I was thinking maybe you could fork the MonoGame.Extended repo, create a new project in the solution called MonoGame.Extended.xTile and see if you can port your code across.

It's really up to you though. I'll be honest, I've already got a lot on my plate at the moment and I wouldn't have much time to do much with it. It's just a thought.

**Comment by colinvella** [comment]
Hi Dylan,

I have some other commitments currently but I'll look into it.

Cheers
Colin
