### ISSUE TITLE
Use StyleCop

### ISSUE THREAD

**Issue by LithiumToast** [craftworkgames/MonoGame.Extended#339]
See https://stylecop.codeplex.com

What do you think @craftworkgames?

**Comment by craftworkgames** [comment]
Yeah maybe.

My personal preference would be that everyone uses Resharper but given that's a commercial product I can't expect everyone to do that.

It's been a while since I've used StyleCop but it might be worth looking into. As long as it doesn't create a bunch of new problems I'm probably okay with it.

**Comment by LithiumToast** [comment]
Yeah, probably better just to do cleanup using ReSharper once in awhile instead of dealing with something new.

**Comment by craftworkgames** [comment]
Agreed.
