### ISSUE TITLE
[Gui] Cursor gets offset when moving camera

### ISSUE THREAD

**Issue by Gixen** [craftworkgames/MonoGame.Extended#356]
https://files.gitter.im/craftworkgames/MonoGame.Extended/Ik5V/2017-03-18-18-55-28.webm

Above is an example of what happens when you have a movable camera. The cursor gets offset the more you move the camera.

I remember having a similar problem a while ago with another project. It had something to do with the viewmatrix. You had to inverse the matrix when moving the camera around. Here's a [stacklink ](https://gamedev.stackexchange.com/questions/21681/how-to-get-mouse-position-relative-to-the-map)about the same problem if you need it.

**Comment by craftworkgames** [comment]
Thanks. I'm aware of this problem, I just haven't had a chance to look into it yet.

I imagine the fix will be relatively simple. The main thing I'm going to need to know is how to reproduce it.

**Comment by Gixen** [comment]
I made a repository [here](https://github.com/Gixen/CameraCursor-test) with the most basic code.
Im still learning using github and sourcetree so stuff may or may not be missing.

**Comment by craftworkgames** [comment]
Oh man, I can't believe I didn't notice this before. All you have to do is change one line, from this:

    var guiRenderer = new GuiSpriteBatchRenderer(GraphicsDevice, titleScreen.Skin.DefaultFont,
        camera.GetViewMatrix);

to this:

    var guiRenderer = new GuiSpriteBatchRenderer(GraphicsDevice, titleScreen.Skin.DefaultFont, 
        viewportAdapter.GetScaleMatrix);

The reason is simple, the camera moves and the viewport adapter doesn't.

Normally, you'll want to have your game scene's controlled by the camera but your GUI sits on top of the scene and is not affected by the camera. With this in mind, note that when you're drawing your scene you'll still want to use the camera's view matrix and draw your scene underneath the GUI like this:

            spriteBatch.Begin(transformMatrix: camera.GetViewMatrix());
            spriteBatch.FillRectangle(new RectangleF(300, 100, 200, 200), Color.Red);
            spriteBatch.End();

            guiSystem.Draw(gameTime);

My apologies for taking so long to figure this out. I actually thought it was some complicated bug when I first saw it.
