### ISSUE TITLE
BitmapFont memory usage.

### ISSUE THREAD

**Issue by LithiumToast** [craftworkgames/MonoGame.Extended#365]
- Use `StringBuilder` for `SpriteBatchExtensions.DrawString` and `BitmapFont.MeasureString`.
- Change `BitmapFont.GetGlyphs` to not return a new array.

![capture2](https://cloud.githubusercontent.com/assets/519592/24582370/883e53bc-16e3-11e7-89b3-2e3da5fa285e.PNG)

**Comment by craftworkgames** [comment]
I had a little look at this tonight and I don't think it's going to be simple.

The only way I could think to not return an array from `GetGlyphs` is to change it to an `IEnumerable<>` and use `yield return`. Unfortunately, that doesn't seem to make the memory allocation problems go away, and in fact I think it might make it worse. Did you have some thing else in mind?

As for using `StringBuilder` I think this could be worth it but it looks like it could be quite a deep refactor so I haven't attempted this yet.

I've actually been thinking about this issue on and off since you posted it and I'm not sure if we can fix it by making changes to `BitmapFont` or any of the existing `DrawString` methods. At least, none that make sense anyway (unless you have something else in mind).

However, I have been tossing around one solution which is to introduce a new type. Some kind of `BitmapFontLabel` of sorts.

The idea is to create labels from fonts and hold the "state" in the label object to avoid repeatedly allocating memory. Something like this:

    _label = bitmapFont.CreateLabel("Hello World!");

On creation of the label we could make the calls to `GetGlyphs` and `MeasureString` and store the result. Then we can update *only* when the text changes:

    _label.Text = "Hello New World!";

This would significantly reduce the memory allocations in most cases since the label text tends to only change on game events like loosing health and rarely changes every frame.

Of course, for this to work correctly, we'd also need to provide some new overloads of `DrawString` that takes one of these `BitmapFontLabel`'s and can render it without allocating any memory.

    _spriteBatch.DrawString(_label); 

What do you think?

**Comment by LithiumToast** [comment]
For use with StringBuilder see what I did [here](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Graphics/Batcher2D.cs#L210). In most cases just replacing the parameter type `string` with `StringBuilder` works. The code for methods just have to be duplicated for each `string` and `StringBuilder` parameter. 

Also notice how that code doesn't call `GetGlyphs`, but does the loop itself and calls `GetCharacterRegion` itself. Using `yield` might work but needs to be profiled.

Also read what Read what [Eric Lippert has to say](http://stackoverflow.com/a/5488242).

**Comment by rds1983** [comment]
I'd suggest two solutions:
1. Simply copy/paste code from BitmapFont.GetGlyphs to BitmapFontExtensions.DrawString. Of course, it looks ugly. Also it would require to support two nodes of code. But it's most obvious and simple solution.
2. Make generic method ProcessGlyphs that takes as glyph processing function as parameter. And call it for both BitmapFont.GetGlyphs and BitmapFontExtensions.DrawString. Of course, it'll cost one more method call for every symbol. But maybe performance cost wouldn't be so substantial?

**Comment by LithiumToast** [comment]
Jus note that in C#, delegates are first class meaning they are objects. The object representing the method will need to be cached to prevent creating a new object every time. This will probably be on the user of the API if a delegate is used to solve this problem.

A probably better solution is to create a custom enumerator `struct` that does the logic of `GetGlyphs`. Then `foreach` can be used without creating a new array.
