### ISSUE TITLE
Support UWP / Windows 10

### ISSUE THREAD

**Issue by Odonno** [craftworkgames/MonoGame.Extended#383]
I wanted to use the Monogame.Extended package in my project but I can't install the NuGet package.

![image](https://cloud.githubusercontent.com/assets/6053067/25547510/bbabfb84-2c67-11e7-95b4-22cdfc64f21f.png)

**Comment by craftworkgames** [comment]
yeah, we currently don't officially support UWP but it should be possible to get it working if you build from source. 

It'd be nice to support it if we can but I'm not sure it's possible without breaking other platforms in the process. Maybe there is a way to do it, I'm not sure. The hard part is testing all the other platforms to make sure they still work too.

If you do get it working I'd love to know about it.

**Comment by claudiuslollarius** [comment]
I am facing the same issue and think the issue is caused by how you create your nugget packages.

In the nuspec files, I see lines like:
`<file src="..\MonoGame.Extended.Tweening\bin\Release\MonoGame.Extended.Tweening.dll" target="lib" />

Following [the convention for multi-targeting nuget packages](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks), by changing to something like:

`<file src="..\MonoGame.Extended.Tweening\bin\Release\MonoGame.Extended.Tweening.dll" target="lib\portable45-net45+win8+wpa81" />

should fix this.

**Comment by claudiuslollarius** [comment]
Created pull request #387 to fix issue. No actual code needed to be changed and should not impact functionality on other platforms.

**Comment by LithiumToast** [comment]
Perhaps we should use .NET standard now.

> Warning
PCLs are not recommended
Although PCLs are supported, package authors should support netstandard instead. The .NET Platform Standard is an evolution of PCLs and represents binary portability across platforms using a single moniker that isn't tied to a static like like portable-a+b+c monikers.

**Comment by craftworkgames** [comment]
Yep. We definitely should got to .NET standard.

It's just not something I've really looked into whole lot. The last time I checked I was under the impression that it wouldn't work because MonoGame would also need to be .NET standard (which I figured wasn't going to happen anytime soon). [Maybe?](https://github.com/MonoGame/MonoGame/issues/5339)

In a more [recent conversation](https://github.com/VelcroPhysics/VelcroPhysics/issues/3) I had with @Genbox (Velcro Physics formerly Farseer) I realized that .NET standard is actually PCL compatible, so it might not be as difficult as I first thought.

If anyone's interested in looking into this more I'm certainly curious of the pros and cons.

**Comment by claudiuslollarius** [comment]
Why is MonoGame not going to move to .NET standard though?

It doesn't look like they have dependencies on anything and moving the shared parts of the codebase from PCL to .NET standard is straightforward.

**Comment by craftworkgames** [comment]
> Why is MonoGame not going to move to .NET standard though?

MonoGame is quite a complicated beast. To be honest I'm not sure of the reasons other than those [already   mentioned](https://github.com/MonoGame/MonoGame/issues/5339) on the .NET Core issue. 

Of course, if you have something contribute, or questions, you should post them on MonoGame's issue.
