### ISSUE TITLE
[Screen] First registered screen is initialized twice

### ISSUE THREAD

**Issue by gotnospirit** [craftworkgames/MonoGame.Extended#405]
Hello,

What do you think about removing the "Initialize" call from "Screen.Show"?

Because "ScreenGameComponent.Register" invokes its first screen's "Show" method, "Screen.Show" calls "Screen.Initialize" and "ScreenGameComponent.Initialize" calls "Initialize" on every screen, when a ScreenGameComponent is initialized its first registered screen is initialized a second time.
depending on what's being done inside the "Initialize" method, this may lead to a memory leak or an exception such as "Cannot Add Same Component Multiple Times"

While we're on it, why not also remove "_screens[0].Show" from "ScreenGameComponent.Register"?

**Comment by craftworkgames** [comment]
Yeah, I agree. That's a good idea.

I've got it on the cards to give the screens code a bit of an overhaul.

**Comment by gotnospirit** [comment]
Ok, i think we don't need a PR since no one else did report this problem.
We can then just wait your refactoring ;)
In the meanwhile, i will use a local version of "Screen.cs" & "ScreenGameComponent.cs" with the changes i suggested.
You can close the issue if you will

**Comment by aravol** [comment]
Seeing the same thing in my game, wherein I'm using DI to load components and screens before initializing either. If the system is meant to pass on `Initialize` from the game component, seems it should only be done on component initialize rather than show, and in either case should keep a private `bool` to prevent multiple calls the way the `Game` class does.
