### ISSUE TITLE
[WPF] Support for WinForms and WPF embedding

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#41]
It occurred to me today that some people are going to [want to make their own levels editors](http://stackoverflow.com/questions/32259666/monogame-and-winforms-drag-and-drop-images) and things like when using MonoGame. 

Embedding MonoGame into WinForms and WPF applications is a bit tricky. I've done it before, and there's certainly things that we might be able to add to the library to help. I'm not sure what those things are yet though. I just wanted to leave this story here for future reference.

Related: http://xbox.create.msdn.com/en-US/education/catalog/sample/winforms_series_1

**Comment by gmich** [comment]
There's a really nice framework for creating IDE-like applications called [Gemini](https://github.com/tgjones/gemini), that has a [WPF control for rendering Monogame in it](https://github.com/tgjones/gemini#monogame-module). 

I use it in my latest [project](https://github.com/gmich/Gem), it's out of the box :)

**Comment by craftworkgames** [comment]
I've been messing around with Gemini a bit over the last few weeks.

Your Gem project looks interesting. I'll have to take a closer look.

**Comment by craftworkgames** [comment]
I've kinda got something along these lines working locally. Not sure exactly how it fits into the library but maybe after we do #275 it'll make more sense.

**Comment by KinoshitaShimizu** [comment]
Hmm, sometime ago I tryied this. What's the current state on this issue? I'll check if I can do something about that later if has not yet been done.

Also, I didn't achieve it, because the solution seemed "abnormal" on the code, so I ended up invoking a clean game instance, controlling it and setting marshallers to GUI and to Game.

**Comment by lithiumtoast** [comment]
Closing due to age. I recommend for any purpose of creating editor tools to use [ImGui](https://github.com/ocornut/imgui) instead. Why? Simply because the editor will run on any target/platform because the editor is embedded inside the game. For .NET there is an existing port with MonoGame support: https://github.com/mellinoe/ImGui.NET.
