### ISSUE TITLE
[ECS] Multiple objects (IndexOutOfRangeException)

### ISSUE THREAD

**Issue by MunWolf** [craftworkgames/MonoGame.Extended#458]
I had a look at issues with IndexOutOfRangeException in the EntityManager.

This does not only happen if you call EntityManager.Scan multiple times but also when you create two or more instances of EntityManager, the first EntityManager doesn't even have to exist anymore as long as you hit it exactly so that (index / 32) goes over the length of the array.

This makes the EntityManager effectively a singleton.

Cheers,
Richard

**Comment by jason2211** [comment]
Hi Richard,
  I ran into the same problem using multiple instances of the ECS.  I tracked it down to the static int (_nextIndex) used in the class EntityComponentType.  This static is used to determine the index of newly created EntityComponents and will be shared between all instances of EntityManager.  

  To fix this, I removed the static int from EntityComponentType and had it passed in by the constructor called from EntityManager.  My EntityManager includes a an instance variable to keep track of the next available component index.  

  After these changes I was able to use two ECS systems in my game.  I was going to make a pull request but I wasn't sure if this was by design or a true bug.  If someone more knowledgeable than I can confirm it is a bug then I'll submit the request.

  You can view my code updates in my repo.  All changes for this "fix" are in a single commit.  https://github.com/jason2211/MonoGame.Extended/commit/2816db61c0521395b2febaacbeb95761eee405a0

Good luck!
Jason

**Comment by craftworkgames** [comment]
> After these changes I was able to use two ECS systems in my game. I was going to make a pull request but I wasn't sure if this was by design or a true bug. If someone more knowledgeable than I can confirm it is a bug then I'll submit the request.

The ECS is a direct port of the [Artemis ECS](https://thelinuxlich.github.io/artemis_CSharp/) which has been a pretty good starting point (as opposed to writing a full ECS from scratch). However, there's certainly plenty of room for improvement.

So, technically, it probably is "by design" but that doesn't mean it's a good design. If there's a good reason to change it then we should probably change it.

**Comment by craftworkgames** [comment]
> This makes the EntityManager effectively a singleton.

Oh, btw. I'm not a fan of the singleton pattern (I'm sure most will agree). I just haven't got around to refactoring this code yet. If you guys are interested in making these improvements I've been working on the ECS in the `2.0` branch lately (among other things).

**Comment by MunWolf** [comment]
Yeah, static/singleton code and variables introduce a global state and that can have some funky consequences, especially if you decide to do some multi-threading, I might help out with this if I can get the time (Have a full time job as a developer and working on my own game so...)

The way Scan is implemented could probably be done better as well.

Cheers,
Richard
