### ISSUE TITLE
TileSetTile null in TiledMapTileObject

### ISSUE THREAD

**Issue by XBLToothPik** [craftworkgames/MonoGame.Extended#470]
While loading a `TMX` map with the `Tiled` extensions, the `TiledMapTileObject` ([HERE](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Tiled/TiledMapTileObject.cs#L15-L20)) constructor tries to locate the `TilesetTile` from the `TileSet.Tiles` with the `FirstOrDefault` method, but it always ends up being null.  This results in the programmer not being able to get the rectangle for the tile for the texture because you cannot get the `LocalIdentifier` that you would pass to `TileSet.GetTileRegion`

Also, it seems as though the `FirstOrDefault` returns null because the `TileSet.Tiles` count is 0?

**Comment by craftworkgames** [comment]
A lot of this code (and a lot of other code) has changed in the `2.0` branch. It's likely that the bug might have been fixed there.

In any case, we need to be able to reproduce the problem. Could you post an example of what you're trying to do when you ran into this problem?

I suspect fixing this in the `develop` branch might be quite tricky. (That's why a lot of stuff has changed in the `2.0` branch) but you're welcome to have a go and submit a PR if you like.

**Comment by craftworkgames** [comment]
Unable to reproduce.
