### ISSUE TITLE
[Particles] Particles Demo creating artifacts in top left window corner

### ISSUE THREAD

**Issue by schmendrick** [craftworkgames/MonoGame.Extended#477]
Hi guys,

I tried to play around with the framework and looked into the particle system but it seems I found an issue. 

Happening for me on:
* branches "2.0", "develop" and "1.0".   (tried with VS2017) of the repository
* official nuget package resharper suggested me: 1.0.617  (tried with VS2013) where i added it to a monogame test project

Behavior seems normal on tag 0.6.359 of the repository.

See image for what I mean:
![image](https://user-images.githubusercontent.com/1175051/36591799-66ae44fc-1893-11e8-8332-27b0afcfa2a6.png)

**Comment by stefanrbk** [comment]
I noticed it as well. I was stepping through the code to try to find what was causing it, but I'm not having much luck myself.

**Comment by craftworkgames** [comment]
It would appear there's a couple of things going on here.

The particles are being triggered by this line in the demo:

```csharp
_particleEffect.Update(deltaTime);
```

and also this line:

```csharp
_particleEffect.Trigger(new Vector2(400, 240));
```

The reason it gets triggered in the `Update` method is because `AutoTrigger` is defaulting to `true` on the emitter.

The reason that it's triggering in the top left corner is because it's using the `Position` property of the emitter as the trigger point.

I suspect this odd behavior was inadvertently to fix another bug. So putting it back to the old behavior might not be the right choice.

I think the "correct" fix to the demo is the remove the `_particleEffect.Trigger(new Vector2(400, 240));` line from the `Update` method and add a `Position = new Vector2(400, 240)` line when creating the particle effect in the `ParticleInit` method.

This will probably suffice to get around the issue in the `develop` branch but I think the real problem here is that the API around this stuff has evolved into something quite confusing. 

One of the goals of `2.0` is to clean up these confusing API's and implement a more consistent and clean approach across the board. It's not entirely clear what that is yet but it's good that these issues are getting raised and discussed. 

My gut feeling at the moment is that having a `Position` on the particle emitter is the wrong choice. It doesn't fit well with the ECS and generally makes it difficult to keep things in sync when it's part of an entity. This also applies when you're not using the ECS. I've been experimenting with this idea on the `Sprite` class in the `2.0` branch but I haven't got around to particles yet.

**Comment by craftworkgames** [comment]
I haven't yet got around to doing a new particles demo. I'll keep this issue open until then.

**Comment by jmwrepos** [comment]
This is the only article I could find on this subject. Possibly out of date, but if you have a similar issue with current version (3.8) then maybe this will be helpful. Solved by updating _particleEffect.Position for my sparkly mouse cursor:


        public override void Update(GameTime gameTime)
        {
            Entities.Cursor.Update();
            var mousePos = Entities.Cursor.Position;
            var m = new Vector2(mousePos.X, mousePos.Y);
            _particleEffect.Update((float)gameTime.ElapsedGameTime.TotalSeconds);
            _particleEffect.Position = new(m.X, m.Y);
        }

        public override void Draw(GameTime gameTime, SpriteBatch spriteBatch)
        {
             spriteBatch.Draw(_particleEffect);            
        }

**Comment by AristurtleDev** [comment]
I am unable to recreate this issue with the current samples in the MonoGame.Extended-samples repository.  If you are still having this issue, please create a new issue ticket with how to recreate it.
