### ISSUE TITLE
[Content] .NET Core Content Pipeline

### ISSUE THREAD

**Issue by WardBenjamin** [craftworkgames/MonoGame.Extended#495]
Since Nuget packages are stored in `~/.nuget/packages` instead of the `./packages` directory for .NET Core projects, the MGCB needs to reference a different path for the `MonoGame.Extended.Content.Pipeline` file - this just needs to be added to the documentation at http://craftworkgames.github.io/MonoGame.Extended/installation/.

I haven't figured out how to make this work with environment variables yet, but this path works for me when hardcoded: 

```/reference:/home/wardp/.nuget/packages/monogame.extended.content.pipeline/1.0.617/tools/MonoGame.Extended.Content.Pipeline.dll```

I'll be opening an issue on the main MonoGame repository about this as well since the solution isn't portable across different platforms/installations - I'll link it momentarily.

What a blast from the past.... _Last contributed on Feb 5, 2016_

**Comment by craftworkgames** [comment]
Now that `develop` is running .NET Core it's a good time to take a look into this issue. I've run into it a couple of times myself.

I think we need to come up with a new (hopefully easier) process for dealing with the MonoGame Content Pipeline tool. It's always been a bit of a pain having to reference the DLL from the packages folder anyway.

I'd appreciate some thoughts on this?

**Comment by WardBenjamin** [comment]
In lieu of a proper solution, such as making the MGCB NuGet-aware, I see two easy options, both of which are somewhat annoying for the end user:

* Manually copy the DLL file from the NuGet cache to a folder relative to the MGCB file, such as inside the content folder
* Do the same as above, but symlink it instead - this has the advantage of not having to copy the DLL every time there's a package update

I'm in favor of the second solution (and am currently using it), but it would have to be very clearly documented.

**Comment by craftworkgames** [comment]
> Do the same as above, but symlink it instead - this has the advantage of not having to copy the DLL every time there's a package update

That's quite a clever idea. I'm not sure if we'll actually be able to automate it but still, it's clever.

> In lieu of a proper solution, such as making the MGCB NuGet-aware

It's entirely possible that we could aim for a "proper" solution rather than some dirty hack. Let's not rule out the possibility of making the MGCB NuGet aware.

Alternately, maybe there's something entirely different we could do. Like build our own content pipeline system?  I mean, we could still use the MGCB compiler to create the XNB files but maybe we can do away with the crappy GUI and have something that builds the content automatically from the command line.

I've been thinking about this idea for a while. Most of the time I just want to build ALL of the content in a folder with default settings. Having to open up the Content Pipeline tool and manually add the file is a huge pain in the ass. I think it should just look a the files in a folder and build the content by default. You could of course still edit the settings in the `Content.mgcb` file if you need to customize something. I love the idea that I can just drop a PNG file into the Content folder and call `Content.Load` without having to do anything else.

Anyway, I'm just spitballing ideas to get the conversation going.

**Comment by LithiumToast** [comment]
@craftworkgames Take a look at [build tools in NuGet](https://natemcmaster.com/blog/2017/11/11/build-tools-in-nuget/). Also, I have been thinking of creating a content pipeline builder tool which is MonoGame independent for quite a while.

**Comment by craftworkgames** [comment]
@LithiumToast Oh man, thanks for that blog post. Super useful. 😄 

I see you've made lots of progress on the build tool 😉 hehe. But seriously, I think it's a good idea.

**Comment by LithiumToast** [comment]
I think that last regex I made on the spot is not quite correct... But anyways, I am pursuing this idea further at https://github.com/Styxz/Assetyard

**Comment by craftworkgames** [comment]
> I think that last regex I made on the spot is not quite correct

The age old problem with regex. 😩 It's complicated. Honestly, I'm not a huge fan of regex for file based pattern matching. I know it's technically more powerful but it comes with a heavy learning curve.

Personally, I'd prefer to use some sort of simpler [globbing pattern](https://github.com/kthompson/glob).

> I am pursuing this idea further 

Sounds great mate. If you get the project off the ground and it works well we'll totally use promote it as the tool to use with MonoGame.Extended rather than building our own custom solution.

**Comment by LithiumToast** [comment]
Sounds good; I'll keep you posted here.

**Comment by craftworkgames** [comment]
btw.. this is the issue that causes a bunch of [builds to fail](http://build.craftworkgames.com/). 😢

**Comment by Apostolique** [comment]
Not sure if you've seen this comment from @cra0zy 

> You can (and should) use the Portable Pipeline Nuget still, this does not change anything about content pipeline extension compilation.

From [here](https://github.com/MonoGame/MonoGame/issues/5339#issuecomment-396029379).

**Comment by cra0zy** [comment]
I'm just gonna correct you guys on something, this issue has nothing to do with .NET Core, it has to do with the new .csproj format... in other words the same issue is applicable to .NET Framework.

**Comment by craftworkgames** [comment]
Thanks @cra0zy. You're right, problem is the `.csproj` format the way I understand it, we have to use the new format because after migrating to .NET Standard.

In any case, there's still quite a bit of confusion about the differences between .NET Core, .NET Standard vs the old PCLs, the old csproj vs the new csproj and so on. 

Can I ask, what do you mean by the "Portable Pipeline Nuget"? Are you talking about [this thing](https://www.nuget.org/packages/MonoGame.Framework.Portable/)?

**Comment by Apostolique** [comment]
It might be the [MonoGame.Framework.Content.Pipeline.Portable](https://www.nuget.org/packages/MonoGame.Framework.Content.Pipeline.Portable/).

**Comment by cra0zy** [comment]
> It might be the MonoGame.Framework.Content.Pipeline.Portable.

Yup.

**Comment by craftworkgames** [comment]
Oh right. That's the one I meant to say.. lol

**Comment by craftworkgames** [comment]
I would like to look into maybe storing the Content Pipeline DLL inside the `tools` folder of the NuGet package. I'm entirely sure if it'll solve this problem because the documentation I've found around it is pretty  vague but I think the next step is to have a play with it and see what happens.

Here are some references I've found while researching this:

 - https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#istool
 - https://natemcmaster.com/blog/2017/11/11/build-tools-in-nuget/
 - https://github.com/NuGet/Home/issues/5020
 - https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#dotnetclitoolreference

**Comment by Raffa50** [comment]
Ehy I can't reference the pipeline ddl, well I did but can't the target doesn't show in the pipeline gui and I can't compile tmx :(

**Comment by craftworkgames** [comment]
> Ehy I can't reference the pipeline ddl, well I did but can't the target doesn't show in the pipeline gui and I can't compile tmx :(

You're not the first person to report this but I still don't know exactly what causes it. Not everyone seems to have this problem.

All I can say is check your versions.  My understanding is that there's a version of MonoGame Pipeline tool that doesn't register the DLL properly for some reason.

**Comment by dararish** [comment]
@Raffa50 
> Ehy I can't reference the pipeline ddl, well I did but can't the target doesn't show in the pipeline gui and I can't compile tmx :(

I was also running into issues while including the MonoGame.Extended.Content.Pipeline.dll. I managed to fix it by placing a copy of MonoGame.Extended.dll, MonoGame.Extended.Tiled.dll, and NewtonSoft.Json.dll in the same directory as the Content.Pipeline dll, and only adding the Content.Pipeline dll as a reference.
![image](https://user-images.githubusercontent.com/5784668/56854506-a4ac0280-6905-11e9-883d-82ae22e23695.png)

**Comment by lithiumtoast** [comment]
This is no longer an issue with 3.8 MonoGame pre-release.
