### ISSUE TITLE
TextureAtlas remove bug

### ISSUE THREAD

**Issue by Apostolique** [craftworkgames/MonoGame.Extended#499]
In TextureAltas, the remove region function is bugged. It make the ints in the ```Dictionary<string, int> _regionMap``` map to the wrong indexes in ```List<TextureRegion2D> _regions```.

**Comment by stefanrbk** [comment]
You are completely right. There is a bug there. `Dictionary<string, int> _regionMap` is to help translate the `string` name to the `int` index of `List<TextureRegion2D> _regions`, but there is nothing to correct the indexes when one is removed from anywhere but the end. I'll check if it's already fixed in `2.0` or not.

**Comment by craftworkgames** [comment]
This is done and merged.
