### ISSUE TITLE
SpriteSheetAnimationFactory and TextureAtlas XML Content Importers

### ISSUE THREAD

**Issue by stefanrbk** [craftworkgames/MonoGame.Extended#505]
I'm working on a project where I'm moving as much hard-coded game content into content files. I was looking at the content importers for `SpriteSheetAnimationFactory` and `TextureAtlas` and I noticed they only support json-based files. I'm much more fluent with xml and I would like to make xml importers for them in the name of flexibility. ;)
What do you guys think of this? Good idea or no?
I could also learn this json thing and make importers for other content types if there isn't one already to give json and xml options for everything.

**Comment by craftworkgames** [comment]
I don't think it's a good idea to have both XML and JSON importers for everything. That's just more code to maintain for very little value.

[JSON.NET](https://www.newtonsoft.com/json) is an excellent library for reading JSON files which is why my preference is always JSON. All of the XML serializers I've used  over the years have been a bit of a pain in the ass compared to JSON.NET. You're experience might be different, but I think you should at least give JSON a try before you dismiss it.

More importantly though, the source file format isn't always in our control. For example, the [Tiled Map Editor](https://www.mapeditor.org/) saves XML files and doesn't support JSON. [BMFont](http://www.angelcode.com/products/bmfont/) also exports to XML (and a couple of others) but doesn't support JSON.

If you want to spend time writing content importers it's more useful to create importers for new tools that we don't currently support or improve the existing importers by adding features they don't already have (for example, I believe there's been some new features added to Tiled since we wrote the importer).

Lastly, learn JSON. It's a really good file format and I'm certain you'll find it useful to have in your toolbox.

**Comment by stefanrbk** [comment]
That sounds like a plan. I've been meaning to work on the Tiled importer. Any other tools we want added? In my project, I haven't run across any others I would really need...

**Comment by Apostolique** [comment]
When you start working with json, you won't want to go back to xml.

**Comment by stefanrbk** [comment]
I know, I've done a few things with it before, but it was more of a pain on the decoding side. I have to keep reminding myself that we have a deserializer and I don't have to make one!

**Comment by craftworkgames** [comment]
Okay, well I'm going to close this now.

@stefanrbk When / if you get around to creating an importer just open a new PR or issue then.
