### ISSUE TITLE
I have a small problem.

### ISSUE THREAD

**Issue by ClEngine** [craftworkgames/MonoGame.Extended#508]
When I used the Tiled library, I found that all the attributes were read-only. Why should I set them read-only when they were designed, can I add them to write attributes? I want to use these properties in the editor and change them.

**Comment by LithiumToast** [comment]
Change them in game? The map is readonly because its expected that map is not dynamic. This includes the tiles. People have asked for dynamic maps before but when asked further about it they have not responded... If you want to read-write attributes in game you can copy the attributes to your own dictionary when loading the map.

**Comment by ClEngine** [comment]
No, I want to make an editor myself, and when I read them in the tiled library, I want to edit their properties for them in my own editor, such as their obstacles, their events.

**Comment by ClEngine** [comment]
Also, I want to change the image position of the image layer, and want to change the location of these image when the tool is compiled.

**Comment by ClEngine** [comment]
@LithiumToast I would like to ask what the consequences will be if we add the writable attributes to them.

**Comment by LithiumToast** [comment]
An editor in game? If not I'm confused; you can create an editor that reads and spits back out the XML (or JSON? is that a thing now?) for the Tiled Map.

**Comment by ClEngine** [comment]
@LithiumToast Maybe there are some problems with my idea. I simply put it. I didn't use the built-in pipeline to compile the resources. I created a resource compiler that uses MGCB to compile. I want to move the picture in the player map to In another folder, and then compile again, but this needs to change the picture location, I can not change its location. Because it is read-only.

**Comment by LithiumToast** [comment]
Again you didn't make it clear if you are trying to edit the map in game or not. If not, then I don't understand exactly what the problem is and is out the scope of MonoGame.Extended. Since you posted here I guess I can assume you do mean in game.

By "compile again" I'm assuming you [want to][are][have] created some sort of tool for development which can load and render the map in game. You then wish to edit the map using this tool and output the XML of the map. You can easily just copy the attributes from the read only data structure to your own data structure and then use that data structure for whatever your needs are. MonoGame.Extended does not currently support outputting the map to original-ish XML that can be used by the Tiled Editor from within game.

**Comment by ClEngine** [comment]
Well, maybe I did something wrong. I will try something else.

**Comment by craftworkgames** [comment]
> No, I want to make an editor myself

This might be something we consider supporting in the future at some point but at this stage it's out of scope. 

You're best bet if you want to do something like this is take the code out of the library and copy it directly into your project. Then you can do what you want with it.

**Comment by ClEngine** [comment]
OK, thank you for allowing me to do this, then I might use your library separately and make some changes.
