### ISSUE TITLE
[Tiled] Missing documentation regarding setting up the content pipeline

### ISSUE THREAD

**Issue by LSpark** [craftworkgames/MonoGame.Extended#528]
Hi, I'm trying to follow the guide here: http://docs.monogameextended.net/Features/Tiled/
But at "Instructions to do so can be found here" I get linked to a 404, could you please fix this? I wouldn't know how to progress otherwise!

**Comment by stefanrbk** [comment]
I submitted a PR to point to that updated address. Hopefully it doesn't break anything... 😅

**Comment by craftworkgames** [comment]
Okay so there's a few things going on here.

The documentation to setup the Content Pipeline is a bit out of date since we migrated things to .NET Standard. Conceptually it's the same but the location of where NuGet installs the DLL's on your machine  has changed (sorry I can't remember where exactly they go off the top of my head).

There's still an open issue #495 that we haven't resolved yet. When we come up with a solution to this problem the process for setting up the Content Pipeline will change (hopefully it'll be easier).

@LSpark The link that @stefanrbk provided is technically the correct place. If you read that documentation and take a look at our demos you can probably figure it out.

@stefanrbk Thanks for updating the link. Keeping out docs up to date is always a challenge and the more people doing it the better.
