### ISSUE TITLE
.NET SDK not supported error when building Extended

### ISSUE THREAD

**Issue by ByTheQuietLake** [craftworkgames/MonoGame.Extended#593]
Hello!
I get the an error when trying to build Monogame.Extended solution which says:

The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.
![extended](https://user-images.githubusercontent.com/47657140/52851867-2e3c9880-313d-11e9-8a3d-8884cd73a21d.png)

I use Visual Studio Community 2017 15.9.7 and choose the .NET desktop development option which installs the following:
![netpackage](https://user-images.githubusercontent.com/47657140/52852083-ac993a80-313d-11e9-855e-953872594a03.png)

Thanks!

**Comment by craftworkgames** [comment]
I'm a little bit confused about what you did to cause this error?

MonoGame.Extended is a .NET Standard 2.0 library which according to [this table](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support) is compatible with .NET Framework 4.6.1.

We've tested this many times and it works just fine. I am using Visual Studio Community 2017 15.9.3 myself.

Oh, wait a second. Maybe the problem is that you need to install [.NET Core](https://dotnet.microsoft.com/download). I'm pretty sure you can select to install this when you install Visual Studio but maybe you didn't?  Either way, I would try that and see how it goes.

**Comment by ByTheQuietLake** [comment]
I selected the .Net desktop development option present in the visual studio installer which by default doesn't seem to install .NET Core and has an option to select .NET Core runtime which needs to be done manually. There seems to be no options to install .NET Core SDK however and I just installed it separately following the link you provided which removes the error that I showed above but unfortunately throws new ones:
![error1](https://user-images.githubusercontent.com/47657140/52858068-24239580-314f-11e9-814f-2ac1ad2a28da.png)
![error2](https://user-images.githubusercontent.com/47657140/52858137-50d7ad00-314f-11e9-84bd-2b2fe54d6162.png)

**Comment by craftworkgames** [comment]
Ah yeah, well those errors look like they are coming from MonoGame's Content builder.

Either you need to install the latest development build of MonoGame from [here](http://teamcity.monogame.net/repository/download/MonoGame_PackagingWindows/latest.lastSuccessful/MonoGameSetup.exe?guest=1) if you haven't already.

Or you need to build the `MonoGame.Extended.Content.Pipeline` project before you build the others. This is a bit of an unfortunate quirk of the way the MonoGame Content Builder works, specifically because it struggles with NuGet package references I think.

Actually, before you do any of that, can you try to run the `build.ps1` file. That should build everything in the right order and run a bunch of tests to make sure everything is working.

Anyway, it's getting late here. I'm off to bed.

**Comment by ByTheQuietLake** [comment]
Thanks for the reply! The SDK not supported error was gone by installing the .NET Core SDK from the link you provided. Other errors did pop up but I as you suggested I will try fiddling around and see if I can remove them. Thanks!
