### ISSUE TITLE
Content.GetSpriteBatch()?

### ISSUE THREAD

**Issue by Shadowblitz16** [craftworkgames/MonoGame.Extended#608]
is there a way to get the sprite batch from a stored ContentManager?

**Comment by craftworkgames** [comment]
You can't really get *the* `SpriteBatch` because you create them yourself. There could be none, one or more than one at any point in time.

You *might* be able to do something like this:

```csharp
var graphicsDeviceManager = (IGraphicsDeviceService) contentManager.ServiceProvider.GetService(typeof(IGraphicsDeviceService));
var spriteBatch = new SpriteBatch(graphicsDeviceManager.GraphicsDevice);
```

I say *might* because there may not be a graphics device manager available depending on the context you need it. 

There's a `ContentManager` extension method called `GetGraphicsDevice` in the library that does something very similar.

**Comment by Shadowblitz16** [comment]
ok thankyou

**Comment by Xaddan** [comment]
Is it possible to do this?
```C#
Services.AddService(new SpriteBatch(GraphicsDevice));
...
Services.GetService<SpriteBatch>();
```
