### ISSUE TITLE
Install 3.7.0 from MGX NuGet Repo, "AndroidGameActivity doesn't exist in the namespace Microsoft.XNA.Framework"

### ISSUE THREAD

**Issue by Malkierian** [craftworkgames/MonoGame.Extended#609]
So I'm trying to get started with MonoGame.Extended, but I'm having trouble in setup.  I have version 3.7.1 of MonoGame.  I'm trying to install the 3.7.0 version of MGX from the craftworkgames.com NuGet server (I also tried 3.6.0 from the NuGet server).  I am able to build the project right off with no problems.  After installing just Monogame.Extended, I can still build the project just fine.  however, after I install the MGX content pipeline, I get this error:
`Activity1.cs(16,54,16,73): error CS0234: The type or namespace name 'AndroidGameActivity' does not exist in the namespace 'Microsoft.Xna.Framework' (are you missing an assembly reference?)`
Weird thing is, I'm certain that installing MGX only added assembly references, and didn't get rid of any.  However, uninstalling Monogame.Extended.Content.Pipeline doesn't fix the issue or return the solution back to its previously working state.  Is this a matter of version incompatibility, and I either need to downgrade my version of MonoGame or wait for MGX to be updated to 3.7.1?

**Comment by craftworkgames** [comment]
First, let me just say I've never seen this particular issue before. However, I'll tell you what I know and maybe we can work something out.

The Content Pipeline support has always been a bit of pain and unfortunately, it became even more difficult  for a few reasons:

 1. NuGet packages -- Microsoft changed -- where they are stored and referenced from.
 2. After moving from Portable Class Libraries to .NET Standard we lost some of the features we used to rely on for the Content Pipeline stuff.

For normal C# programs this all works okay, but the MonoGame Content Pipeline is a custom bit of software implemented by the MonoGame team and it doesn't support NuGet packages per se. 

I suspect what is happening is that the `MonoGame.Extended.Content.Pipeline` package is referencing the old PCL version of MonoGame and is somehow replacing the Android version of the MonoGame reference. It's really quite confusing, even I'm struggling to wrap my head around it.

I think I really need to sit down a spend a good chunk of time to work out an alternative approach to this problem.

**Comment by Malkierian** [comment]
So, then, how do I get around that?  Should I not use the pipeline, or is there a way of installing it without NuGet that would work better?

**Comment by Apostolique** [comment]
Don't know if that's the fix, but in my libraries, I use the following line in the csproj: `<PackageReference Include="MonoGame.Framework.Portable" PrivateAssets="All" Version="3.6.0.1625" />`

In MonoGame.Extended.Content.Pipeline, you have: `<PackageReference Include="MonoGame.Framework.Content.Pipeline.Portable" Version="3.6.0.1625" />`

In MonoGame.Extended, you use `PrivateAssets="All"` like I did.

https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Content.Pipeline/MonoGame.Extended.Content.Pipeline.csproj#L26

https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/MonoGame.Extended.csproj#L21

That's probably all it is.

**Comment by craftworkgames** [comment]
> So, then, how do I get around that?

Okay, I've had a little time to think this over. Although, I still haven't found the time to try and reproduce the issue I think I can help you work around it.

Essentially the goal is to separate the Content Pipeline DLL's from the game DLL's. In other words, you don't want to be using NuGet to reference the `MonoGame.Extended.Content.Pipeline` package in your game.

The way it used to work according to [these out of date instructions](http://docs.monogameextended.net/Installation/) is that you'd reference the NuGet package and it would put the DLL's into your local `packages` folder but it *would not* reference them into your game. Unfortunately, this is no longer the case with changes made to the way NuGet packages interact with `dotnet` projects.

As for the best way to work around this, I'm not exactly sure yet. However, my first thought would be to add another project to your solution and reference the `MonoGame.Extended.Content.Pipeline` package from it instead. This will allow NuGet to download the package and have the DLL's available to you but you'll need to figure out where it puts them.

Once you know the path, you should be able to reference the DLL's from the `Content.mgcb` file as per normal. Remember, the only purpose of this is so you can build your content. The Game itself doesn't ever need to reference the `MonoGame.Extended.Content.Pipeline` package.

>  Should I not use the pipeline, or is there a way of installing it without NuGet that would work better?

To address the second part of your question, I have some thoughts about creating an alternative tool that could be used to build Content outside the MonoGame Content Pipeline. Under the hood, it would still be doing the same thing, but it could have some other benefits like being able to build content without the need to "add" it to the `Content.mgcb` file using a GUI and also some sort of "hot-reloading".

As for using NuGet, the problem is essentially that the Content Pipeline doesn't support adding references this way (you have to manually go through the GUI to add it) which is a huge pain in the butt.  
To deal with this I guess there are 2 options. First, we could provide another way to download the DLL's (maybe just a zip file on the website) or alternatively there might be a way to have a "real" project reference the NuGet package like the old XNA Content projects used to do.

Sorry, I got a little carried away there 😄 (end of rant).

**Comment by Malkierian** [comment]
Alright, I did some digging in the csproj files, and in the file before adding the Extended pipeline, I have this reference:
```<Reference Include="MonoGame.Framework">
      <HintPath>$(MonoGameInstallDirectory)\MonoGame\v3.0\Assemblies\Android\MonoGame.Framework.dll</HintPath>
    </Reference>```
But after installing the pipeline, I find that it has replaced that reference with this:
```<Reference Include="MonoGame.Framework, Version=3.6.0.1625, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\MonoGame.Framework.Portable.3.6.0.1625\lib\portable-net45+win8+wpa81\MonoGame.Framework.dll</HintPath>
    </Reference>```
Soooo, I removed that and put back the one that MonoGame specified itself, and it's not giving me any errors again.  Whether it will work or not is another story, but at least I can build it.  Now to see if I can figure out just how to use the pipeline...  Especially with the LibGDX skins that I want to try.

**Comment by JoshuaLamusga** [comment]
I'm only getting version 1.1 in Nuget.
![image](https://user-images.githubusercontent.com/30244654/60377345-c475aa80-99ca-11e9-8721-b3875bf850d5.png)

I take it the version should be around 3.6? Discovered this shortly when using Matrix2D and seeing the example uses Matrix2 instead. Only two outdated references to Matrix2D in comments in the actual source today.
