### ISSUE TITLE
MonoKickstart and mkbundle not working with MonoGame.Extended

### ISSUE THREAD

**Issue by Ellpeck** [craftworkgames/MonoGame.Extended#616]
When I try to either use [MonoKickstart](https://github.com/MonoGame/MonoKickstart) or [mkbundle](https://www.mono-project.com/docs/tools+libraries/tools/mkbundle/) to publish a MonoGame project that also uses MonoGame.Extended, I get this issue:

![image](https://user-images.githubusercontent.com/5741138/60759570-8cecab00-a027-11e9-8ceb-e8fe43e0f000.png)
(when bundling MonoKickstart and trying to run it)

![image](https://user-images.githubusercontent.com/5741138/60759572-9fff7b00-a027-11e9-8f3a-ffb2a9d5f0a3.png)
(when trying to bundle it using mkbundle)

When not having MonoGame.Extended as part of the project, this issue doesn't happen. I tested with both 1.1.0 and 3.6.0-beta0001.

**Comment by craftworkgames** [comment]
Sorry, I have no experience with MonoKickstart or mkbundle so I'm not sure how to interpret the error.

If I had to guess, I'd say that MonoKickstart and mkbundle probably don't currently support .NET Standard 2.0 which is what MonoGame.Extended target. 

The good news is that all of the code in Extended should be very standard C#. There's no cross platform trickiness or anything of that nature. So your best best would be to compile the code yourself and make any tweaks necessary to get it working.

**Comment by Ellpeck** [comment]
What's your suggestion on how to publish a game that uses MonoGame.Extended that should work cross-platform?

**Comment by craftworkgames** [comment]
To be honest I haven't published a Linux game myself but I don't see any reason why it can't be done. We target .NET Standard 2.0 which is compatible with most platforms as [shown in this table](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support).

A while back, we did have some Android and Linux based demos but unfortunately there hasn't been anyone around to maintain them. Like I said though, none of the code in the actual library is platform specific, so it should work.

More than likely the problem you're seeing has more to do with something external to the code itself. Maybe the NuGet packages or the way the MonoGame.Framework.dll gets bundled into the game.

In the early days, to get MonoGame.Exteneded to work we had to do the [bait and switch PCL trick](https://log.paulbetts.org/the-bait-and-switch-pcl-trick/) and to some degree this is still the case. Basically what this means is that the MonoGame DLL's that are loaded into memory at runtime are different to the ones used to build the library in the first place. We do this because MonoGame isn't really cross platform. It uses different DLL's depending on which platform you're targeting. The only other way around this is to compile Extended for every platform in the same way MonoGame does.

Essentially what this means is you can always get Extended to work if you compile it yourself because you can reference the same MonoGame DLL's used in your game and make sure there's nothing hairy going with DLL "switching" at runtime. 

If you want a sure fire way to get this to work, try getting the Extended source code out on your machine in a directory structure like this (assuming your game code is in a `git` folder).

- git
   - MonoGame.Extended
   - YourGame

Then remove the NuGet references and replace them with project references. Compile your code and it should work the same.

Once you've got this setup I'll bet mkbundle works as expected.

**Comment by Ellpeck** [comment]
Thanks, I'll try that out!
