### ISSUE TITLE
TiledMap ArgumentException Unclear As To What Problem Is

### ISSUE THREAD

**Issue by manbeardgames** [craftworkgames/MonoGame.Extended#617]
If you import a Tiled map (.tmx) that contains two or more layers with the same name, an `ArgumentException` is thrown in the [AddLayer method of the TiledMap class.](https://github.com/craftworkgames/MonoGame.Extended/blob/130daf3e5e7dc02e1b2abc6244553314fd147eac/Source/MonoGame.Extended.Tiled/TiledMap.cs#L72)

This happens because `_layersByName` is a Dictionary object using `layer.Name` as the key. When the layer is added, if one already exists, the ArgumentException is thrown.

If you are using MonoGame.Extended from a NuGet package, when this exception is thrown, the only thing you see as the user is 
```
System.ArgumentException: 'An item with the same key has already been added.'
```

Looking at the stack trace for the exception, you can see the AddLayer method mentioned

```
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at MonoGame.Extended.Tiled.TiledMap.AddLayer(TiledMapLayer layer) in C:\TeamCity\buildAgent\work\8dee3b4a1a2bbd93\Source\MonoGame.Extended.Tiled\TiledMap.cs:line 81
```

From an end user perspective though, it is quite unclear as to why this exception is thrown and can be very confusing and frustrating. 

I would like to suggest adding a check before adding the layer to see if the key exists. If it does exist, manually thrown an exception explaining why.  Something like the following:

```csharp
if (_layersByName.ContainsKey(layer.Name))
{
    throw new Exception($"The TiledMap \"{Name}\" contains two or more layers named \"{layer.Name}\". Please ensure all layers have unique names.");
}
```

**Comment by craftworkgames** [comment]
Yeah, I this is a good idea. It's always bothered me that the default `ArgumentException` doesn't tell you what key has already been added. I mean it's gotta be right there when they throw right?

Just a couple of things to consider:

 - Generally speaking it's better practice to throw something a little more specific instead of `Exception`. I would usually suggest [throwing `InvalidOperationException`](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions#use-the-predefined-net-exception-types) but in this case keeping it as a `ArgumentException` will be a non-breaking change (in case someone is already catching that type of exception).

 - Unfortunately, whenever you're working with dictionaries there's always a small performance penalty to pay if you need to call `ContainsKey` before calling `Add` since it'll need to lookup the key twice. However, given that this is not a performance critical part of the code I don't see this a problem. I think the main reason it wasn't implemented this way before is because I didn't actually realize you could have a duplicate layer name in Tiled.

- Lastly, let's just tweak the string slightly so that we don't need to escape the quotes. This not only cleans up the code but it makes it easier to copy and paste the error into Google and other such things.

**Comment by manbeardgames** [comment]
A way of alleviating the performance cost of calling `ContainsKey` on the dictionary is to keep a HashSet of just the layer names.  Then check the HashSet if it contains the value first..

**Comment by craftworkgames** [comment]
> Actually just realized that a Dictionary uses a Hash for the key already.

Yeah, that's correct. It was an interesting idea though and I appreciate thinking outside the box.

Unfortunately, even if storing the layer names in a `HashSet` was faster we'd have a new problem. Keeping the `HashSet` in sync with the `Dictionary` would make inserts and deletes slower and the code more complex.

The good news is that your comment got me thinking about what else could be done and I think I came up with a solution. 

```csharp
try 
{
    _layersByName.Add(layer.Name, layer);
}
catch(ArgumentException ex)
{
    throw new ArgumentException(ex, $"The TiledMap '{Name}' contains two or more layers named '{layer.Name}'. Please ensure all layers have unique names.");
}
```

Instead of calling `ContainsKey` for every call to `AddLayer` we could instead handle the exception by wrapping it in a new exception. This way we're adding more information to the exceptional case without needing to do any extra work in the non-exceptional case.

I believe this would technically be the best of both worlds without any downside. Although, I've never run a performance profiler over code like this so I'm not entirely certain (it's possible that adding the `try` `catch` block changes the IL in some way that outweighs the performance penalty of using `ContainsKey`).  

In either case, I don't think performance is ever going to be a problem anyway. It's very unlikely anybody would ever need to call `AddLayer` in performance critical code and it's even more unlikely they'd have more than a handful of layers (if they've got a lot of layers there'd be much bigger problems). 

I really just posted my thoughts here because I think it's an interesting thought experiment. Even though it makes no measurable difference in this code it seems useful to have this knowledge in case we need it in the future.

I'll merge the PR now :)

**Comment by manbeardgames** [comment]
Thanks for the merge.  Given that without a`try-catch` or `ContainsKey` in this situation, an exception would be thrown anyway, i think either solution would would work. The goal of the PR was to just wrap the exception already being thrown to make it more clear as to what caused the exception.  

Another solution to this could be to check the layer names during the processing of the .tmx file in the content pipeline extension.  I haven't looked it over in depth, but maybe in [`ProcessLayers` method in the TiledMapProcessor](https://github.com/craftworkgames/MonoGame.Extended/blob/26cfd55ef9d918d10a9e3aae057b27be73da46da/Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapProcessor.cs#L124)?  Could use a `HashSet` there for each layer being processed and if a name collision occurs, the exception could be thrown there. 

This would eliminate the need for the check in the framework since we're stopping it before runtime occurs.


------
I just want to add this information here really quickly since you mentioned the try-catch block. [Here's a stack overflow answer](https://stackoverflow.com/a/13194904) that compares timing performance of `try-catch` vs `ContainsKey`. Performance is negligible unless your expecting the `try` to fail frequently. 

As for the IL code, there is a small overhead added for the `try-catch`. 

<details>
  <summary>Expand to view MSIL code</summary>
  <p>

The code below was generated using [.NET Fiddle](https://dotnetfiddle.net/)

</p>
  
C#
```csharp
public static void NoTryCatch()
{
	dictionary.Add("key", "value");
}
```

MSIL:
```
  .method public hidebysig static void  NoTryCatch() cil managed
  {
    // 
    .maxstack  8
    IL_0000:  nop
    IL_0001:  ldsfld     class [mscorlib]System.Collections.Generic.Dictionary`2<string,string> Program::dictionary
    IL_0006:  ldstr      "key"
    IL_000b:  ldstr      "value"
    IL_0010:  callvirt   instance void class [mscorlib]System.Collections.Generic.Dictionary`2<string,string>::Add(!0,
                                                                                                                   !1)
    IL_0015:  nop
    IL_0016:  ret
  } // end of method Program::NoTryCatch
```

C#
```csharp
public static void TryCatch()
{
	try
	{
		dictionary.Add("key", "value");
	}
	catch (ArgumentException ex)
	{
		throw new ArgumentException("The TiledMap 'mapName' contains two or more layers named 'layerName'. Please ensure all layers have unique names.", ex);
	}
}
```

MSIL
```MSIL
.method public hidebysig static void  TryCatch() cil managed
  {
    // 
    .maxstack  3
    .locals init (class [mscorlib]System.ArgumentException V_0)
    IL_0000:  nop
    .try
    {
      IL_0001:  nop
      IL_0002:  ldsfld     class [mscorlib]System.Collections.Generic.Dictionary`2<string,string> Program::dictionary
      IL_0007:  ldstr      "key"
      IL_000c:  ldstr      "value"
      IL_0011:  callvirt   instance void class [mscorlib]System.Collections.Generic.Dictionary`2<string,string>::Add(!0,
                                                                                                                     !1)
      IL_0016:  nop
      IL_0017:  nop
      IL_0018:  leave.s    IL_0028

    }  // end .try
    catch [mscorlib]System.ArgumentException 
    {
      IL_001a:  stloc.0
      IL_001b:  nop
      IL_001c:  ldstr      "The TiledMap 'mapName' contains two or more layers"
      + " named 'layerName'. Please ensure all layers have unique names."
      IL_0021:  ldloc.0
      IL_0022:  newobj     instance void [mscorlib]System.ArgumentException::.ctor(string,
                                                                                   class [mscorlib]System.Exception)
      IL_0027:  throw

    }  // end handler
    IL_0028:  nop
    IL_0029:  ret
  } // end of method Program::TryCatch
```

</details>

**Comment by craftworkgames** [comment]
Nice work. Very detailed explanation.
