### ISSUE TITLE
MonoSpaced Font helper?

### ISSUE THREAD

**Issue by Shadowblitz16** [craftworkgames/MonoGame.Extended#630]
can a helper method be added to easily create monospaced bitmap fonts?
something like...

```cs
MonoSpacedBitmapFont(Texture2D texture, int charWidth, int charHeight, string charMap, int borderX=0, int borderY=0, int spacingX=0, int spacingY=0);
```

note that it takes a texture2d and a string
creating something from this..
![image](https://user-images.githubusercontent.com/2453707/64391481-b614c200-cffd-11e9-8771-60b2d9b605fd.png)
would only require this...
```cs
var nesfont = game.Content.Load<Texture2D>("nesfont");
MonoSpacedBitmapFont(nesfont, 8, 8, " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz(|)~");
```

**Comment by Apostolique** [comment]
Have you tried SpriteFontPlus? https://github.com/rds1983/SpriteFontPlus

**Comment by Shadowblitz16** [comment]
no this looks like it used formatted bitmap fonts and ttfs
It would be much easier to create one directly from image.

I would like to not have to use any 3rd party program besides a image editing program.

**Comment by craftworkgames** [comment]
It's actually not too difficult to roll this yourself using the existing `BitmapFont` class.

```cs
const string characters = @" !""#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~";
var monospacedTexture = Content.Load<Texture2D>("Fonts/monospaced");
var atlas = TextureAtlas.Create("monospaced-atlas", monospacedTexture, 16, 16);
var fontRegions = new BitmapFontRegion[characters.Length];
var index = 0;

for (var y = 0; y < monospacedTexture.Height; y += 16)
{
    for (var x = 0; x < monospacedTexture.Width; x += 16)
    {
        if (index < characters.Length)
        {
            fontRegions[index] = new BitmapFontRegion(atlas[index], characters[index], 0, 0, 16);
            index++;
        }
    }
}

_bitmapFontMonospaced = new BitmapFont("monospaced", fontRegions, 16);
```

And then of course, you render it just like any other.

```cs
_spriteBatch.DrawString(_bitmapFontMonospaced, "Hello Monospaced Fonts!", new Vector2(100, 400), Color.White);
```

![image](https://user-images.githubusercontent.com/3201643/64425162-5ba75e80-d0ee-11e9-822b-4028d2197ad1.png)

Oh, and rather than let this neat little snippet of code go to waste, I've added to the [font demo](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/Demos/Features/Demos/BitmapFontsDemo.cs#L43) 😄 

I'll consider adding a helper method to do this maybe, but to be honest I think it's a rare enough request that just having it the demo will probably be enough.

**Comment by Shadowblitz16** [comment]
I will look into this but i think it would still be a nice use for monogame.extended.
this would be so nice and easier to create fonts for people that do not have full knowledge of the monogame interworkings.

**Comment by craftworkgames** [comment]
The thing is, most people are happy to use [BMFont](https://www.angelcode.com/products/bmfont/) to create a regular `BitmapFont` or the MonoGame Content Pipeline to create a `SpriteFont`. Either approach works just fine and creating fonts for your game is not something people typically do all that often.

In the 4 years since I started MonoGame.Extended I've never had anyone else ask about creating fonts this way. Adding a helper to Extended to do this is not as trivial as you might think and it's simply not worth the effort if nobody else ever uses it. Maybe they would, maybe they wouldn't. There just isn't enough evidence either way.

You might not have a full knowledge of MonoGame and that's fine. I don't mind helping people solve these kinds of problems. The above code is literally everything you need to know to get your monospaced font working. A simple thank you would be appreciated.
