### ISSUE TITLE
inputlisseners support of keycombos 

### ISSUE THREAD

**Issue by christopherpross** [craftworkgames/MonoGame.Extended#662]
Hey,
the inputlisseners are not updated since 3 years, I don't know why, maybe this is a way, which is not fast enugth?
Eneway, I use them, but I could not use keycombos with them.
Because in the eventargs, there are only given one key, not all keys from the input state.
It is possible to fix that?

all the best,
Chriss

**Comment by lithiumtoast** [comment]
The input listeners are just call-backs for when *a key* has happened. For games, I'm really not that much of a fan because, as you already figured out, I usually want to check multiple keys at once at a specific time.

I think re-visiting the `MonoGame.Extended.Input` is a good idea. Be about the right to figure out an excellent way to support:
- Key mappings/combos
- Re-mapping of keys
