### ISSUE TITLE
`TiledMapRenderer` constructor throws exception: "This MGFX effect is for an older release of MonoGame and needs to be rebuilt"

### ISSUE THREAD

**Issue by craxal** [craftworkgames/MonoGame.Extended#686]
I am attempting to use a small Tiled map in a MonoGame, following the MonGame.Extended example. Content and code compile successfully, but when I run the game, I get an exception when constructing the `TiledMapRenderer` with the following message:

> This MGFX effect is for an older release of MonoGame and needs to be rebuilt
> at Microsoft.Xna.Framework.Graphics.Effect.ReadHeader(Byte[] effectCode, Int32 index)
   at Microsoft.Xna.Framework.Graphics.Effect..ctor(GraphicsDevice graphicsDevice, Byte[] effectCode, Int32 index, Int32 count)
   at MonoGame.Extended.Graphics.Effects.MatrixChainEffect..ctor(GraphicsDevice graphicsDevice, Byte[] byteCode)
   at MonoGame.Extended.Graphics.Effects.DefaultEffect..ctor(GraphicsDevice graphicsDevice)
   at MonoGame.Extended.Tiled.Renderers.TiledMapRenderer..ctor(GraphicsDevice graphicsDevice, TiledMap map)

Developing in Visual Studio 2019
MonoGame 3.8.0.1375
MonoGame.Extended 3.7.0
MonoGame.Content.Builder.Task 3.8.0.1375-develop

I'm a bit new to this, but but I wouldn't be surprised if the issue is with the different versions of MonoGame and MonoGame.Extended. However, I can only find the one version of MonoGame in the NuGet repo, so downgrading doesn't seem to be an option.

Also, in case it matters, the test map is an isometric map.

**Comment by lithiumtoast** [comment]
There is no NuGet package for `MonoGame.Extended` that works with MonoGame 3.8 pre-release, yet. Building MonoGame.Extended from source would allow you to use MonoGame 3.8.

**Comment by craxal** [comment]
Yeah, that works. Thanks for the help.

I just noticed that MonoGame 3.8. How often do you release updates? Or how closely behind MonoGame releases do you usually follow?

**Comment by lithiumtoast** [comment]
> How often do you release updates?

Whenever necessary given the bounded time I have. I would like to achieve something closer to having channels of "nightly" and "planned" builds using NuGet packages. Any changes to the `develop` branch would automatically get deployed to a pre-release labelled by a semantic version. More stable releases while Git tags (also labelled by semantic version) would be used whenever appropriate but not more than twice a calendar quarter.

That being said, I'm in the midst of solving some high-level technical decisions about `MonoGame.Extended` since I'm taking new ownership. These challenges, for the time being, are preventing me from doing what I said I would like to achieve above.

> how closely behind MonoGame releases do you usually follow?

As soon as possible. I will look into resolving this issue this weekend. I wish they would announce ahead of time when a release will happen but then again I guess it's my fault as I could easily keep better track of the GitHub discussions and pull-requests of MonoGame to reasonably guess that information.

**Comment by craxal** [comment]
@lithiumtoast Thanks for the info. Much appreciated!

**Comment by lithiumtoast** [comment]
Re-opening until #687 is finished.
