### ISSUE TITLE
[Particle] Dispose causes app-crash

### ISSUE THREAD

**Issue by EnemyArea** [craftworkgames/MonoGame.Extended#745]
If you dispose an particle it crashes without exception. The console-window displays a message like: wurde mit Code -1073740940 (0xc0000374) beendet.
It seems that the memory is not released correctly.
You can reproduce it in te samples if you add this code to the Update 

            if (keyboardState.IsKeyDown(Keys.F10))
                _particleEffect.Dispose();

after pressing F10, it crashes
Edit: found the issue: https://github.com/craftworkgames/MonoGame.Extended/pull/581
It was this pullrequest, thats brokes it,

Edit2: nope, it stilll broken, sometimes it works, sometimes not...
Edit3: after some research I think it can by fixed by simply adding a IsDisposed property to the ParticleEmitter, that stop the update:

            if (Buffer.Count == 0 || this.IsDisposed)
                return false;

And in the ParticleExtensions

        private static unsafe void UnsafeDraw(SpriteBatch spriteBatch, ParticleEmitter emitter)
        {
            if(emitter.TextureRegion == null || emitter.IsDisposed)
                return;

Then, the error went away.

**Comment by AristurtleDev** [comment]
I am unable to reproduce this issue with the current `develop` branch.  However, looking at the chain of dispose that happens here, it is not implementing the standard dispose patterns. Not only this, but even after dispose, the objects continue to function as if they weren't disposed, which is not an expected behavior.

Will refactor this to better implement the dispose pattern.

**Comment by AristurtleDev** [comment]
Closed with #879
