### ISSUE TITLE
Collision spots are not correct

### ISSUE THREAD

**Issue by Advancensar** [craftworkgames/MonoGame.Extended#77]
The layer you get from Tiledmap is not in correct place or checking the collision bounds is not working as intended, collision works fine when the coordinates are at the starting index. If check bounding box on columns only chance is vertical, and for rows it is horizontal.It is feels like a loop for bounding box has an extra multiplier.
Hopefully i made it clear, my knowledge about programming is limited so is my English.

Gif presentation of the issue.
https://gfycat.com/BlushingAnnualAntipodesgreenparakeet

**Comment by Advancensar** [comment]
Changing             
return world.CreateGrid(data, tileLayer.Width, tileLayer.Height, tileLayer.TileWidth, tileLayer.TileHeight);
To
return world.CreateGrid(data, tileLayer.Width, tileLayer.Height, tileLayer.TileWidth-1, tileLayer.TileHeight-1);
In CollisionWorldExtensions is a workaround for now, if anyone needs to use collision detection.

**Comment by craftworkgames** [comment]
Good to know. I took a quick look at the renderer yesterday and I don't think it's a bug in MonoGame after all. 

I think the real problem is the way the camera scales the sprites; leaving tiny gaps between the tiles at certain zoom levels because each Sprite is scaled individually.

The good news is I've got an idea how to do it properly using a render target so I'll have a go at it soon. Unfortunately I've got a really busy weekend but I'll get to it as soon as possible.

**Comment by craftworkgames** [comment]
@Advancensar Sorry, I've been busy today. I was at the the [YOW developer conference](http://yowconference.com.au/) here in Brisbane all day.

So I looked into this a bit more and found the problem.

It's kind of embarrassing actually... lol. A few months ago when I implemented the rendered I noticed an issue with gaps between the tiles. My first thought was that I had a bug in my code. 

I tested, tweaked and debugged the code for hours eventually convincing myself the bug was somewhere else. I assumed that the bug must be in MonoGame, so I wrote a little workaround by offsetting the tiles by 1 pixel. I had always intended to get back to it but as the code seemed to be working it was forgotten.

Digging a little deeper I finally realized the problem wasn't in the code. It was actually in the sprite sheet I was using for testing! Some of the tiles in the sprite sheet where 1 pixel larger than others causing some of them to be packed together with 3 pixels of spacing instead of 2!

Anyway, I removed the workaround from the code and fixed the sprite sheet. Everything is working as expected now :smile:

**Comment by craftworkgames** [comment]
There was still a small problem with *tearing* between tiles but I eliminated that with a render target in commit https://github.com/craftworkgames/MonoGame.Extended/commit/dd367a709faa19976b93160eee866de4fc517149

That should close off this issue.
