### ISSUE TITLE
Fail to create TiledMapImporter

### ISSUE THREAD

**Issue by EzNoGame** [craftworkgames/MonoGame.Extended#792]
The tilemaps have already loaded in mcgb file
![image](https://user-images.githubusercontent.com/71359408/196051221-38155197-31a4-43f6-9f69-b4d419b8b7af.png)
![image](https://user-images.githubusercontent.com/71359408/196051241-c6b189c1-5847-4a5f-b2f9-dc11d5cf4e04.png)

**Comment by BumpkinRich** [comment]
In the .mcgb file check the location of the MonoGame.Extended.Content.Pipeline.dll. Ensure that is a valid path.

**Comment by AristurtleDev** [comment]
No response from initial reply on issue.  This was most likely caused due to needing MonoGame.Extended updated for MonoGame 3.8.1.303. 

Until the MonoGame.Extended v4.0.0 release you can use one of the following workaround
1. Use the source code of MonoGame.Extended directly and reference it in your project
2. Use the most recent (at the time of writing this) prerelease NuGet https://www.nuget.org/packages/MonoGame.Extended/3.9.0-prerelease.4

If your issue is still present after trying these workaround, please open a new issue
