### ISSUE TITLE
Resolution Independence almost working

### ISSUE THREAD

**Issue by lionelthomas** [craftworkgames/MonoGame.Extended#80]
It is basically working except that I cannot change the window size. I start with a 1000X550 window and a virtual game area of 800X550. It pillarboxes properly and the mouse is properly initialized. Are you not supposed to be able to change the window size dynamically?
When I go to fullscreen the graphics are correct but I can't seem to initialize my inputHandler because it is in a separate component and I can't detect when the game is in fullscreen mode.
This is part of a much larger issue on how to gain access to game variables in library classes.
Thanks.

**Comment by craftworkgames** [comment]
You'll need to hook up the OnClientSizeChanged event.

http://dylanwilson.net/resolution-independence-in-monogame-with-viewport-adapters

**Comment by lionelthomas** [comment]
I have hooked up the OnClientSizeChanged event thus:
Window.ClientSizeChanged += (s, e) => OnClientSizeChanged();
takes me to:
void OnClientSizeChanged()
{
       _viewportAdapter.OnClientSizeChanged();
       input.MouseHandler.Initialize(_viewportAdapter);
       graphics.ApplyChanges();
 }
This creates a loop and gives a stack overflow.
graphics.ApplyChanges(); appears to raise the OnClientSizeChanged()

Should it do this?

**Comment by lionelthomas** [comment]
It is now clear to me that GraphicsDevice.Viewport does not contain the dimensions of the new size OnClientSizeChanged but the existing dimensions. Consequently, the BoxingViewportAdapter does not do the right calculation. The virtual size stays the same and the offset equals zero. If you initialize the viewport it appears to work. Not sure if MonoGame 3.5 fixes this. I can't see a workaround.

**Comment by craftworkgames** [comment]
> It is now clear to me that GraphicsDevice.Viewport does not contain the dimensions of the new size 

I remember seeing some issues related to this when I wrote the viewport adapters but I can't recall the exact details. What platform are you targeting? Are you using the GL or DX version of MonoGame?

> Consequently, the BoxingViewportAdapter does not do the right calculation.

Have you managed to compile and run the samples? The [viewport adapters sample](https://github.com/craftworkgames/Samples.Extended/blob/master/Source/Samples.Extended/Samples/ViewportAdaptersSample.cs) should cover most of what you need to know to get it working.

> graphics.ApplyChanges(); appears to raise the OnClientSizeChanged()
> Should it do this?

As you've noticed calling ApplyChanges in the OnClientSizeCanaged event is a bad idea. What happens if you take out that line?

As seen in the sample, the only thing that matters when you're using the boxing viewport adapter is that the `OnClientSizeChanged` method on the viewport adapter is called when the `Window.OnClientSizeChanged` event is fired.

You can of course do other things in the event handler if you wish, but keep it simple to start with and see how it goes.

**Comment by lionelthomas** [comment]
After much ennui, I have determined that MonoGame GraphicsDeviceManager.ApplyChanges() is indeed incorrectly raising the OnClientSizeChanged Event. There is an issue that deals with this https://github.com/mono/MonoGame/issues/3572. This creates problems when you want to change the ViewPort. If you place the ApplyChanges in the OnClientSizeChanged event then you get an infinite loop. If you place it in the Update it executes the ViewPortAdapter over and over again. Leaving it out means that the viewportadapter effectively doesn't work.

Also the ViewportAdapter incorrectly uses the dimensions of the GraphicsDevice.Viewport it should use the dimensions of the Window which are changed when the OnClientSizeChanged is fired. It appears to work because the Viewport is initialized correctly but in mid game it has no effect because it keeps using the existing dimensions. Another problem is the real dimensions of fullscreen including or excluding borders. I have passed the Window dimensions through the EventArgs and that works fine but because we can't apply the changes we can't change the window size mid game.

If you can think of a way to Apply the changes. then we can get this to work mid game.

**Comment by craftworkgames** [comment]
Interesting findings, but there must be something else going on because I haven't been able to reproduce your issue.

You can indeed change the window size mid game in the viewport adapters sample and there's no need to call `ApplyChanges()`.

My guess is that there's some differences in the way the GL and DX version of MonoGame are implemented.

**Comment by craftworkgames** [comment]
I attempted to implement the `BoxingViewportAdapter` by injecting the game window into the constructor..

        public BoxingViewportAdapter(GraphicsDevice graphicsDevice, GameWindow gameWindow, int virtualWidth, int virtualHeight)
            : base(graphicsDevice, virtualWidth, virtualHeight)
        {
            _gameWindow = gameWindow;
            _gameWindow.ClientSizeChanged += GameWindowOnClientSizeChanged;
        }

And listening to the client size changed event directly rather than having to call it from the Game class.

        private void GameWindowOnClientSizeChanged(object sender, EventArgs eventArgs)
        {
            var newWidth = _gameWindow.ClientBounds.Width;
            var newHeight = _gameWindow.ClientBounds.Height;
            var aspectRatio = (float)VirtualWidth / VirtualHeight;
            var width = newWidth;
            var height = (int)(width / aspectRatio + 0.5f);

            if (height > newHeight)
            {
                BoxingMode = BoxingMode.Pillarbox;
                height = newHeight;
                width = (int)(height * aspectRatio + 0.5f);
            }
            else
            {
                BoxingMode = BoxingMode.Letterbox;
            }

            var x = (newWidth / 2) - (width / 2);
            var y = (newHeight / 2) - (height / 2);
            GraphicsDevice.Viewport = new Viewport(x, y, width, height);
        }

Unfortunately, even though the code appears to be correct and the viewport is being set to the correct size at the end of the event something inside MonoGame is resetting the Viewport after the event is fired. I don't think this is correct behavior and is probably related to issue https://github.com/mono/MonoGame/issues/3572

If I get a chance this week I'll look into it further and try push a fix to MonoGame.

**Comment by lionelthomas** [comment]
Thank you, I thought that I might be going a bit crazy

**Comment by craftworkgames** [comment]
Ah ha!!

It's most certainly a difference between the GL and DX versions.

If you reference the GL version (the problem goes away)

    C:\Program Files (x86)\MonoGame\v3.0\Assemblies\WindowsGL\MonoGame.Framework.dll

vs the DX version (the problem appears)

    C:\Program Files (x86)\MonoGame\v3.0\Assemblies\Windows\MonoGame.Framework.dll

Hopefully that's a workaround for you?

**Comment by lionelthomas** [comment]
I will try that thanks.
I just found a very annoying thing about references in my VS2015. I try to set a reference by selecting from the list and it gives me the wrong one and strange problems appear. When I browse for the reference explicitly I get the right one the problem goes away. Maybe this will be the reason why I can't load samples.
I will try your suggestion, Thanks.

**Comment by craftworkgames** [comment]
Turns out I actually reported this issue to MonoGame a while back https://github.com/mono/MonoGame/issues/4018

**Comment by lionelthomas** [comment]
Just referenced WindowsGL and my version works like a charm. Did have a problem loading a Song though. Will have to look at that. What is the difference between Windows and WindowsGL?
For now this issue is closed. Thank you so much.

**Comment by Yothri** [comment]
I still had this issue and i can confirm that DX still has the problem whilst GL does not. Cant this be fixed?!

**Comment by craftworkgames** [comment]
> I still had this issue and i can confirm that DX still has the problem whilst GL does not. Cant this be fixed?!

What version of MonoGame / MonoGame.Extended are you using?

**Comment by Yothri** [comment]
> What version of MonoGame / MonoGame.Extended are you using?

Erm, I think I downloaded the MonoGame for Visual Studio from the website.

**Comment by Yothri** [comment]
Oh crap, I think i messed up here. 
I dont know how i get here but i am not even using Extended. 

What i just noticed is that when i create a windows project i cant use AppyChanges() in the window resize event, but as soon as i use same code in a desktop gl project everything seems to work fine. I should create an issue in monogame repository?

**Comment by craftworkgames** [comment]
> I should create an issue in monogame repository?

Yep. Sounds like you need to create a new issue [over here](https://github.com/MonoGame/MonoGame/issues)
