### ISSUE TITLE
i need you come back! for monogame version 3.8.1~~~

### ISSUE THREAD

**Issue by RicharDKcoder** [craftworkgames/MonoGame.Extended#811]
so, like title, i need you come back for update monogame extended for monogame laster version 3.8.1

tiled extended not work better...

**Comment by AristurtleDev** [comment]
This is no longer an issue in `develop` since it has been updated to the latest MonoGame version. 

Until the MonoGame.Extended v4.0.0 release you can use one of the following workaround
1. Use the source code of MonoGame.Extended directly and reference it in your project
2. Use the most recent (at the time of writing this) prerelease NuGet https://www.nuget.org/packages/MonoGame.Extended/3.9.0-prerelease.4
