### ISSUE TITLE
MonoGame.Extended.Tiled Need to update!!!!!!!!!!!!

### ISSUE THREAD

**Issue by wijat** [craftworkgames/MonoGame.Extended#826]
Can not build this in MonoGame 3.8.1.

**Comment by AristurtleDev** [comment]
Issue is vague and doesn't provide details. However this is no longer an issue in `develop` since it has been updated to the latest MonoGame version. 

Until the MonoGame.Extended v4.0.0 release you can use one of the following workaround
1. Use the source code of MonoGame.Extended directly and reference it in your project
2. Use the most recent (at the time of writing this) prerelease NuGet https://www.nuget.org/packages/MonoGame.Extended/3.9.0-prerelease.4
