### ISSUE TITLE
SVG importer and drawer?

### ISSUE THREAD

**Issue by cra0zy** [craftworkgames/MonoGame.Extended#90]
For anyone who doesn't know, SVG stands for Scalable Vector Graphics, and is created, as the name implies, out of vectors instead of pixels.

**Comment by craftworkgames** [comment]
Vector graphics are rarely used to make games.

Why do you want this?

**Comment by cra0zy** [comment]
> Vector graphics are rarely used to make games.

Not true, anything made in flash is vector based.

> Why do you want this?

Vector based stuff can be scaled without loosing quality.

**Comment by craftworkgames** [comment]
> Not true, anything made in Flash is vector based.

That's true. Flash is one of the exceptions to this rule. When I said vector graphics are rarely used, what I meant was that not many *game engines* support vector graphics. 

There could be a [number of reasons](http://gamedev.stackexchange.com/questions/30111/why-dont-more-games-use-vector-art) for this. I believe it's mostly because a GPU is [not really optimized to render that way](http://programmers.stackexchange.com/questions/191472/why-have-hardware-accelerated-vector-graphics-not-taken-off).

Regardless of the reason, I just don't think there's a market for it within the MonoGame community. I could be wrong of course, but that's how I feel about it right now. If you can provide some evidence to the contrary, you're welcome to prove me wrong.

**Comment by stromkos** [comment]
I thought I would weigh in on this topic. 

There were arcade games developed that utilized vector graphics.  The monitors had a special control board that accepted **only** vector graphics.  How times have 



>Not true, anything made in Flash is vector based.
All motion in Flash is vector based, but what is being moved can be vector or raster based.

The resources required to rasterize a vector image every step would be unwieldy. 

That being said, I am all for a content importer that supports SVG and .ai (Adobe Illustrator) vector graphics.  That would **almost** require compile time rasterization with mipmapping.(See below)

However, I believe that this would be better placed in the MonoGame content importers for general use. 

--
After many hours of internal debate, I have developed an idea...


If you can create proper multiple triangle-fan vertex point structures utilizing only lines (i.e. triangles, not arcs, ellipses, or circles) and vertex colors from a SVG file, drawing a vector graphic reduces to a simple scaling 3D mesh matrix transformation. That is definitely feasible with modern hardware.  

I do not have the time to implement such an interface, but if I did, I would add a pull request for a new content importer to the MonoGame community, and not here.

@craftworkgames, I hope, I am not overstepping boundaries with my idea of the scope of this project.

**Comment by craftworkgames** [comment]
> That being said, I am all for a content importer that supports SVG and .ai (Adobe Illustrator) vector graphics. 

Yeah, something like that seems more likely.

> If you can create proper multiple triangle-fan vertex point structures utilizing only lines (i.e. triangles, not arcs, ellipses, or circles) and vertex colors from a SVG file, drawing a vector graphic reduces to a simple scaling 3D mesh matrix transformation.

Interesting idea. I would be interested to see how well this works, but I'm not going to rush out and do it myself. I just don't think there's enough demand for something like this. Of course, that's just my opinion and I could be very wrong.

> @craftworkgames, I hope, I am not overstepping boundaries with my idea of the scope of this project.

Not at all. I think it's great to debate about this stuff.
